---
title: "Project 2: Biomedical & Clinical Informatics"
subtitle: "Merrimack College DSE6630: Healthcare & Life Sciences Analytics"
author: "Katherine S. Geist, PhD"
date: "29 April 2024"
output:
  html_document:
    toc: true
    toc_float: true
    theme: flatly
bibliography: ../Demo/references.bib  
nocite: '@*'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      cache = TRUE,
                      cache.comments = TRUE,
                      size = 13)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
# Turn off scientific notation
options(scipen=999)

# Set seed
set.seed(50009)


# Clean, set up, and load
pacman::p_unload(pacman::p_loaded(), character.only = TRUE)
rm(list = ls(all = TRUE))

pacman::p_load(tidyverse,
               janitor,
               naniar,
               stringr,
               ggplot2, 
               kableExtra,
               RColorBrewer,
               gridExtra,
               ggrepel,
               e1071,
               caret
)
```

# Functions to Help
```{r}

```


# Introduction

# Load Data
```{r}
load("../Demo/pneumoniaAnalyze.Rdata")
```

Finish the data preparation:


# EDA
```{r}
# What is the distribution of violent hate crimes by bias description?
pneumoniaAnalyze %>%
  rename(NatlComparisonDeathRate = `ComparedToNational_Death rate for pneumonia patients`) %>% 
  mutate(NatlComparisonDeathRate = ifelse(NatlComparisonDeathRate == 1, "Above Average", 
                                   ifelse(NatlComparisonDeathRate == -1, "Below Average", 
                                    ifelse(NatlComparisonDeathRate == 0, "Same as Average", NatlComparisonDeathRate)))) %>% 
  select(contains(c("Score", "NatlComparisonDeathRate", "PredictedReadmissionRate"))) %>% 
  pivot_longer(-NatlComparisonDeathRate, names_to = "Variable", values_to = "Value")


  ggplot(aes(x = as.factor(violent), y = Value, fill = as.factor(violent))) +
    geom_col(position = "dodge") + 
    labs(title = "Mean Numbers of Biases by Hate Crime Type",
        x = "",
        y = "Mean Value",
        fill = "Violent Hate Crime") +
  scale_fill_manual(values = c("cadetblue", "gold"), labels = c("True", "False")) + 
  theme_grey() +
  theme(legend.position = "bottom",
        axis.text.x = element_blank(),
        axis.ticks.x = element_blank()) + 
  facet_wrap(~Variable) 
```

