% Options for packages loaded elsewhere
\PassOptionsToPackage{unicode}{hyperref}
\PassOptionsToPackage{hyphens}{url}
\documentclass[
]{article}
\usepackage{xcolor}
\usepackage[margin=1in]{geometry}
\usepackage{amsmath,amssymb}
\setcounter{secnumdepth}{-\maxdimen} % remove section numbering
\usepackage{iftex}
\ifPDFTeX
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
  \usepackage{textcomp} % provide euro and other symbols
\else % if luatex or xetex
  \usepackage{unicode-math} % this also loads fontspec
  \defaultfontfeatures{Scale=MatchLowercase}
  \defaultfontfeatures[\rmfamily]{Ligatures=TeX,Scale=1}
\fi
\usepackage{lmodern}
\ifPDFTeX\else
  % xetex/luatex font selection
\fi
% Use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
\IfFileExists{microtype.sty}{% use microtype if available
  \usepackage[]{microtype}
  \UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\makeatletter
\@ifundefined{KOMAClassName}{% if non-KOMA class
  \IfFileExists{parskip.sty}{%
    \usepackage{parskip}
  }{% else
    \setlength{\parindent}{0pt}
    \setlength{\parskip}{6pt plus 2pt minus 1pt}}
}{% if KOMA class
  \KOMAoptions{parskip=half}}
\makeatother
\usepackage{color}
\usepackage{fancyvrb}
\newcommand{\VerbBar}{|}
\newcommand{\VERB}{\Verb[commandchars=\\\{\}]}
\DefineVerbatimEnvironment{Highlighting}{Verbatim}{commandchars=\\\{\}}
% Add ',fontsize=\small' for more characters per line
\usepackage{framed}
\definecolor{shadecolor}{RGB}{248,248,248}
\newenvironment{Shaded}{\begin{snugshade}}{\end{snugshade}}
\newcommand{\AlertTok}[1]{\textcolor[rgb]{0.94,0.16,0.16}{#1}}
\newcommand{\AnnotationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\AttributeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\BaseNTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\BuiltInTok}[1]{#1}
\newcommand{\CharTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\CommentTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\CommentVarTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ConstantTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\ControlFlowTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\DataTypeTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{#1}}
\newcommand{\DecValTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\DocumentationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\ErrorTok}[1]{\textcolor[rgb]{0.64,0.00,0.00}{\textbf{#1}}}
\newcommand{\ExtensionTok}[1]{#1}
\newcommand{\FloatTok}[1]{\textcolor[rgb]{0.00,0.00,0.81}{#1}}
\newcommand{\FunctionTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\ImportTok}[1]{#1}
\newcommand{\InformationTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\newcommand{\KeywordTok}[1]{\textcolor[rgb]{0.13,0.29,0.53}{\textbf{#1}}}
\newcommand{\NormalTok}[1]{#1}
\newcommand{\OperatorTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\OtherTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{#1}}
\newcommand{\PreprocessorTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textit{#1}}}
\newcommand{\RegionMarkerTok}[1]{#1}
\newcommand{\SpecialCharTok}[1]{\textcolor[rgb]{0.81,0.36,0.00}{\textbf{#1}}}
\newcommand{\SpecialStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\StringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\VariableTok}[1]{\textcolor[rgb]{0.00,0.00,0.00}{#1}}
\newcommand{\VerbatimStringTok}[1]{\textcolor[rgb]{0.31,0.60,0.02}{#1}}
\newcommand{\WarningTok}[1]{\textcolor[rgb]{0.56,0.35,0.01}{\textbf{\textit{#1}}}}
\usepackage{graphicx}
\makeatletter
\newsavebox\pandoc@box
\newcommand*\pandocbounded[1]{% scales image to fit in text height/width
  \sbox\pandoc@box{#1}%
  \Gscale@div\@tempa{\textheight}{\dimexpr\ht\pandoc@box+\dp\pandoc@box\relax}%
  \Gscale@div\@tempb{\linewidth}{\wd\pandoc@box}%
  \ifdim\@tempb\p@<\@tempa\p@\let\@tempa\@tempb\fi% select the smaller of both
  \ifdim\@tempa\p@<\p@\scalebox{\@tempa}{\usebox\pandoc@box}%
  \else\usebox{\pandoc@box}%
  \fi%
}
% Set default figure placement to htbp
\def\fps@figure{htbp}
\makeatother
% definitions for citeproc citations
\NewDocumentCommand\citeproctext{}{}
\NewDocumentCommand\citeproc{mm}{%
  \begingroup\def\citeproctext{#2}\cite{#1}\endgroup}
\makeatletter
 % allow citations to break across lines
 \let\@cite@ofmt\@firstofone
 % avoid brackets around text for \cite:
 \def\@biblabel#1{}
 \def\@cite#1#2{{#1\if@tempswa , #2\fi}}
\makeatother
\newlength{\cslhangindent}
\setlength{\cslhangindent}{1.5em}
\newlength{\csllabelwidth}
\setlength{\csllabelwidth}{3em}
\newenvironment{CSLReferences}[2] % #1 hanging-indent, #2 entry-spacing
 {\begin{list}{}{%
  \setlength{\itemindent}{0pt}
  \setlength{\leftmargin}{0pt}
  \setlength{\parsep}{0pt}
  % turn on hanging indent if param 1 is 1
  \ifodd #1
   \setlength{\leftmargin}{\cslhangindent}
   \setlength{\itemindent}{-1\cslhangindent}
  \fi
  % set entry spacing
  \setlength{\itemsep}{#2\baselineskip}}}
 {\end{list}}
\usepackage{calc}
\newcommand{\CSLBlock}[1]{\hfill\break\parbox[t]{\linewidth}{\strut\ignorespaces#1\strut}}
\newcommand{\CSLLeftMargin}[1]{\parbox[t]{\csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLRightInline}[1]{\parbox[t]{\linewidth - \csllabelwidth}{\strut#1\strut}}
\newcommand{\CSLIndent}[1]{\hspace{\cslhangindent}#1}
\setlength{\emergencystretch}{3em} % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\usepackage{booktabs}
\usepackage{longtable}
\usepackage{array}
\usepackage{multirow}
\usepackage{wrapfig}
\usepackage{float}
\usepackage{colortbl}
\usepackage{pdflscape}
\usepackage{tabu}
\usepackage{threeparttable}
\usepackage{threeparttablex}
\usepackage[normalem]{ulem}
\usepackage{makecell}
\usepackage{xcolor}
\usepackage{bookmark}
\IfFileExists{xurl.sty}{\usepackage{xurl}}{} % add URL line breaks if available
\urlstyle{same}
\hypersetup{
  pdftitle={Demo 1: Biomedical \& Clinical Informatics},
  pdfauthor={Katherine S. Geist, PhD},
  hidelinks,
  pdfcreator={LaTeX via pandoc}}

\title{Demo 1: Biomedical \& Clinical Informatics}
\usepackage{etoolbox}
\makeatletter
\providecommand{\subtitle}[1]{% add subtitle to \maketitle
  \apptocmd{\@title}{\par {\large #1 \par}}{}{}
}
\makeatother
\subtitle{Merrimack College DSE6630: Healthcare \& Life Sciences
Analytics}
\author{Katherine S. Geist, PhD}
\date{12 May 2026}

\begin{document}
\maketitle

{
\setcounter{tocdepth}{2}
\tableofcontents
}
\section{Introduction}\label{introduction}

You have just been brought on as a data science consultant for a patient
advocacy watchdog. They have asked you to source information about
hospital readmissions, because they would like to flag specific
geographic areas or types of hospitals where hospital readmission is
unexpectedly high. They have heard that datasets exist to investigate
these types of questions, but they are not really sure where to begin.

You remember this one data science class you took - and the dataset from
the \textbf{Centers for Medicare \& Medicaid Services} managed by
\href{https://www.medicare.gov}{Medicare.gov}. You start poking around
the
\href{https://data.cms.gov/provider-data/topics/hospitals}{Hospitals}
dataset and decide it is exactly what you need.

The problem is, this dataset is massive, so you are not only tasked with
identifying a reasonable question you can ask from the dataset but
managing the cleaning, pre-processing, and exploratory data analysis on
the merged datasets you choose to explore.

\subsection{Question}\label{question}

For \textbf{Project 1}, you are going to choose your own question! But
for this demo analysis, we are focusing on \textbf{pneumonia-related
hospital readmissions}.

\subsubsection{Why pneumonia-related
readmissions?}\label{why-pneumonia-related-readmissions}

Hospital readmission rates for patients with pneumonia is almost
unbelievably high, with about \(\frac{1}{5}\) or 20\% of patients
hospitalized with pneumonia re-admitted within 30 days (de Alba and
Amin, 2014). Further, pneumonia is both a leading cause of death among
the elderly as well as a commonly communicated disease in hospitals (as
in, people may come into a hospital for a different condition but be
readmitted for pneumonia). Thus, given that pneumonia is the only
communicable disease on this list, it is serving as our best proxy for
diseases spread person-to-person within hospitals because of lack of
availability.

\paragraph{Our research question:}\label{our-research-question}

Can we predict pneumonia-related hospital readmissions and, more
generally, disease transfer within hospitals, based on hospital-level
characteristics, including patient-ratings, Medicare money received, and
other indicators of general performance in disease diagnosis and
prevention?

\paragraph{Our hypothesis \&
prediction:}\label{our-hypothesis-prediction}

Hospitals are, by their very nature, hot zones for increased spread of
disease, including pneumonia. We hypothesize that hospitals with lower
indicators of patient care performance and lower Medicare funding rates
will generally be unable to provide sufficient control of specific
disease diagnosis and prevention, like pneumonia. This is because the
same intrinsic and extrinsic factors that impact general patient quality
of care is likely to extend to pneumonia, a \emph{common, preventable,
and treatable} disease. Thus, we specifically predict that factors
indicating lower quality-of-care will predict higher than average rates
of pneumonia-related hospital readmissions.

\subsection{Objective}\label{objective}

Our objective for the patient advocacy watchdog is clean, merge,
explore, and predict which hospitals tend to have higher-than-average
rates of pneumonia-related readmissions. This is to enable the watchdog
group to put together a dashboard or otherwise deploy this information
to share with patients so they know how their local hospitals are
performing, allowing them to make healthier, more informed choices.

\section{Data \& Data Cleaning}\label{data-data-cleaning}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Download the
  \href{https://data.cms.gov/provider-data/topics/hospitals}{Hospitals}
  dataset as a zip directory.
\item
  Unzip the directory.
\item
  Make sure to adjust the name and/or path of the directory in your
  directory if it is different from mine. \emph{Note that mine is living
  on my Desktop.}
\end{enumerate}

\textbf{WARNING!} Do not try to put these data onto GitHub. They are too
large to push. If you need help adjusting your path or have questions,
please let me know.

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\# Make sure to adjust your path!}
\NormalTok{filepath }\OtherTok{\textless{}{-}} \StringTok{"\textasciitilde{}/Development/R\_workspaces/hospitals\_current\_data/"}

\FunctionTok{dir.exists}\NormalTok{(filepath)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# What\textquotesingle{}s actually in the folder?}
\FunctionTok{list.files}\NormalTok{(filepath)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "ASC_Facility.csv"                                                
##  [2] "ASC_National.csv"                                                
##  [3] "ASC_State.csv"                                                   
##  [4] "ASCQR_OAS_CAHPS_BY_ASC.csv"                                      
##  [5] "ASCQR_OAS_CAHPS_NATIONAL.csv"                                    
##  [6] "ASCQR_OAS_CAHPS_STATE.csv"                                       
##  [7] "Birthing_Friendly_Hospitals_Geocoded.csv"                        
##  [8] "CJR_Quality_Reporting_January_2026_Production_File.csv"          
##  [9] "CMS_PSI_6_decimal_file.csv"                                      
## [10] "Complications_and_Deaths-Hospital.csv"                           
## [11] "Complications_and_Deaths-National.csv"                           
## [12] "Complications_and_Deaths-State.csv"                              
## [13] "Data_Updates_April_2026.csv"                                     
## [14] "Footnote_Crosswalk.csv"                                          
## [15] "FY_2026_HAC_Reduction_Program_Hospital.csv"                      
## [16] "FY_2026_Hospital_Readmissions_Reduction_Program_Hospital.csv"    
## [17] "FY2024_Distribution_of_Net_Change_in_Base_Op_DRG_Payment_Amt.csv"
## [18] "FY2024_Net_Change_in_Base_Op_DRG_Payment_Amt.csv"                
## [19] "FY2024_Percent_Change_in_Medicare_Payments.csv"                  
## [20] "FY2024_Value_Based_Incentive_Payment_Amount.csv"                 
## [21] "HCAHPS-Hospital.csv"                                             
## [22] "HCAHPS-National.csv"                                             
## [23] "HCAHPS-State.csv"                                                
## [24] "Healthcare_Associated_Infections-Hospital.csv"                   
## [25] "Healthcare_Associated_Infections-National.csv"                   
## [26] "Healthcare_Associated_Infections-State.csv"                      
## [27] "HOSPITAL_Data_Dictionary.pdf"                                    
## [28] "Hospital_General_Information.csv"                                
## [29] "HOSPITAL_QUARTERLY_MSPB_6_DECIMALS.csv"                          
## [30] "hvbp_clinical_outcomes.csv"                                      
## [31] "hvbp_efficiency_and_cost_reduction.csv"                          
## [32] "hvbp_person_and_community_engagement.csv"                        
## [33] "hvbp_safety.csv"                                                 
## [34] "hvbp_tps.csv"                                                    
## [35] "IPFQR_QualityMeasures_Facility.csv"                              
## [36] "IPFQR_QualityMeasures_National.csv"                              
## [37] "IPFQR_QualityMeasures_State.csv"                                 
## [38] "Maternal_Health-Hospital.csv"                                    
## [39] "Measure_Dates.csv"                                               
## [40] "Medicare_Hospital_Spending_by_Claim.csv"                         
## [41] "Medicare_Hospital_Spending_Per_Patient-Hospital.csv"             
## [42] "Medicare_Hospital_Spending_Per_Patient-National.csv"             
## [43] "Medicare_Hospital_Spending_Per_Patient-State.csv"                
## [44] "OQR_OAS_CAHPS_BY_HOSPITAL.csv"                                   
## [45] "OQR_OAS_CAHPS_NATIONAL.csv"                                      
## [46] "OQR_OAS_CAHPS_STATE.csv"                                         
## [47] "Outpatient_Imaging_Efficiency-Hospital.csv"                      
## [48] "Outpatient_Imaging_Efficiency-National.csv"                      
## [49] "Outpatient_Imaging_Efficiency-State.csv"                         
## [50] "PATIENT_REPORTED_OUTCOMES_FACILITY.csv"                          
## [51] "PCH_Complications_Unplanned_Hospital_Visits_HOSPITAL.csv"        
## [52] "PCH_Complications_Unplanned_Hospital_Visits_NATIONAL.csv"        
## [53] "PCH_HCAHPS_HOSPITAL.csv"                                         
## [54] "PCH_HCAHPS_NATIONAL.csv"                                         
## [55] "PCH_HCAHPS_STATE.csv"                                            
## [56] "PCH_HEALTHCARE_ASSOCIATED_INFECTIONS_HOSPITAL.csv"               
## [57] "PCH_Palliative_Care_HOSPITAL.csv"                                
## [58] "PCH_Palliative_Care_NATIONAL.csv"                                
## [59] "Promoting_Interoperability-Hospital.csv"                         
## [60] "readme.txt"                                                      
## [61] "REH_Outpatient_Imaging_Efficiency-Hospital.csv"                  
## [62] "REH_Outpatient_Imaging_Efficiency-National.csv"                  
## [63] "REH_Timely_and_Effective_Care-Hospital.csv"                      
## [64] "REH_Timely_and_Effective_Care-National.csv"                      
## [65] "REH_Unplanned_Hospital_Visits-Hospital.csv"                      
## [66] "REH_Unplanned_Hospital_Visits-National.csv"                      
## [67] "Timely_and_Effective_Care-Hospital.csv"                          
## [68] "Timely_and_Effective_Care-National.csv"                          
## [69] "Timely_and_Effective_Care-State.csv"                             
## [70] "Unplanned_Hospital_Visits-Hospital.csv"                          
## [71] "Unplanned_Hospital_Visits-National.csv"                          
## [72] "Unplanned_Hospital_Visits-State.csv"                             
## [73] "VA_IPF.csv"                                                      
## [74] "VA_TE.csv"                                                       
## [75] "Veterans_Health_Administration_Provider_Level_Data.csv"
\end{verbatim}

\subsubsection{Read in the hospital-level data iteratively, while
dynamically naming \& storing each file as a
dataframe.}\label{read-in-the-hospital-level-data-iteratively-while-dynamically-naming-storing-each-file-as-a-dataframe.}

You may have to dig through the accompanying data dictionary
\textbf{HOSPITAL\_Data\_Dictionary.pdf} to get a better handle on what
is in the hospital-level files.

\subparagraph{\texorpdfstring{\textbf{Question 1}: {[}1
point{]}}{Question 1: {[}1 point{]}}}\label{question-1-1-point}

Take a look at the chunk below, which performs \textbf{dynamic variable
assignment} as it reads in each of the files. Your task is to add a
comment to each line of code to describe what that line does.

\begin{quote}
Your answer in the code chunk as comments. Make sure to use the
\texttt{\#} sign!
\end{quote}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Get a list of files in the directory whcih match pattern "Hospital.csv"}
\NormalTok{files }\OtherTok{\textless{}{-}} \FunctionTok{list.files}\NormalTok{(}\AttributeTok{path =}\NormalTok{ filepath, }\AttributeTok{pattern =} \StringTok{"Hospital.csv"}\NormalTok{)}

\CommentTok{\# Loop through each files in files list}
\ControlFlowTok{for}\NormalTok{(f }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(files)) \{}
    \CommentTok{\# read each csv file, change column names to upperCamelCase format}
\NormalTok{    dat }\OtherTok{\textless{}{-}} \FunctionTok{clean\_names}\NormalTok{(}\FunctionTok{read\_csv}\NormalTok{(}\FunctionTok{paste0}\NormalTok{(filepath, files[f]),}
                                \AttributeTok{show\_col\_types =} \ConstantTok{FALSE}\NormalTok{), }
                       \AttributeTok{case =} \StringTok{"upper\_camel"}\NormalTok{)}
    \CommentTok{\# Create a variable name by removing ".Hospital.csv" suffix from the filename}
\NormalTok{    filename }\OtherTok{\textless{}{-}} \FunctionTok{gsub}\NormalTok{(}\StringTok{".Hospital}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{.csv"}\NormalTok{, }\StringTok{""}\NormalTok{, files[f])}
    \CommentTok{\# Dynamically create a variable in the global environment named \textquotesingle{}filename\textquotesingle{} holding the data}
    \FunctionTok{assign}\NormalTok{(filename, dat)}
\NormalTok{\}}

\CommentTok{\# Strip ".Hospital.csv" suffix from all filenames and convert the resulting vector into a data frame}
\NormalTok{files }\OtherTok{\textless{}{-}} \FunctionTok{gsub}\NormalTok{(}\StringTok{".Hospital}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{.csv"}\NormalTok{, }\StringTok{""}\NormalTok{, files) }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{data.frame}\NormalTok{()}

\CommentTok{\# Rename the single column of the \textquotesingle{}files\textquotesingle{} data frame to "File Name" for readability}
\FunctionTok{names}\NormalTok{(files) }\OtherTok{\textless{}{-}} \StringTok{"File Name"}
\end{Highlighting}
\end{Shaded}

\paragraph{Now, let's look at a list of the files that we've read
in:}\label{now-lets-look-at-a-list-of-the-files-that-weve-read-in}

Table 1. List of hospital-level data files.

File Name

Complications\_and\_Deaths

FY\_2026\_HAC\_Reduction\_Program

FY\_2026\_Hospital\_Readmissions\_Reduction\_Program

HCAHPS

Healthcare\_Associated\_Infections

Maternal\_Health

Medicare\_Hospital\_Spending\_Per\_Patient

Outpatient\_Imaging\_Efficiency

Promoting\_Interoperability

REH\_Outpatient\_Imaging\_Efficiency

REH\_Timely\_and\_Effective\_Care

REH\_Unplanned\_Hospital\_Visits

Timely\_and\_Effective\_Care

Unplanned\_Hospital\_Visits

\subparagraph{\texorpdfstring{\textbf{Question 2}: {[}1
point{]}}{Question 2: {[}1 point{]}}}\label{question-2-1-point}

Take a look at some of the dataframes, e.g., \texttt{HCAHPS} and
\texttt{FY\_2024\_Hospital\_Readmissions\_Reduction\_Program}. What do
you notice about the format / structure of the data? Does the data have
an issue with the dimensionality? \textbf{Hint: }Check to see if each
row represents a single line of data or not!

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# Helper function: print a clean summary for any dataframe}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{inspect\_df }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(df, df\_name, id\_col) \{}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"============================================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"  Dataset:"}\NormalTok{, df\_name, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"============================================================}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
    
    \CommentTok{\# Basic dimensions}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"\textgreater{}\textgreater{} Dimensions (rows x columns):}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"   Rows:    "}\NormalTok{, }\FunctionTok{format}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(df), }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"   Columns: "}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(df), }\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
    
    \CommentTok{\# Column names}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"\textgreater{}\textgreater{} Column names:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{print}\NormalTok{(}\FunctionTok{names}\NormalTok{(df))}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    
    \CommentTok{\# Unique hospitals vs total rows}
\NormalTok{    n\_unique }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(df[[id\_col]]))}
\NormalTok{    n\_rows   }\OtherTok{\textless{}{-}} \FunctionTok{nrow}\NormalTok{(df)}
\NormalTok{    ratio    }\OtherTok{\textless{}{-}} \FunctionTok{round}\NormalTok{(n\_rows }\SpecialCharTok{/}\NormalTok{ n\_unique, }\DecValTok{1}\NormalTok{)}
    
    \FunctionTok{cat}\NormalTok{(}\StringTok{"\textgreater{}\textgreater{} Unique hospitals vs total rows:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"   Unique hospitals ("}\NormalTok{, id\_col, }\StringTok{"): "}\NormalTok{, }
        \FunctionTok{format}\NormalTok{(n\_unique, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"   Total rows:                    "}\NormalTok{, }
        \FunctionTok{format}\NormalTok{(n\_rows, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"   Avg rows per hospital:         "}\NormalTok{, ratio, }\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
    
    \CommentTok{\# Verdict}
    \ControlFlowTok{if}\NormalTok{ (ratio }\SpecialCharTok{\textgreater{}} \FloatTok{1.1}\NormalTok{) \{}
        \FunctionTok{cat}\NormalTok{(}\StringTok{"\textgreater{}\textgreater{} VERDICT: LONG FORMAT detected}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
        \FunctionTok{cat}\NormalTok{(}\StringTok{"   Each hospital appears in \textasciitilde{}"}\NormalTok{, ratio, }
            \StringTok{" rows on average.}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, }\AttributeTok{sep =} \StringTok{""}\NormalTok{)}
        \FunctionTok{cat}\NormalTok{(}\StringTok{"   This is a dimensionality issue — data needs to be}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
        \FunctionTok{cat}\NormalTok{(}\StringTok{"   pivoted to WIDE format for one{-}row{-}per{-}hospital analysis.}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{    \} }\ControlFlowTok{else}\NormalTok{ \{}
        \FunctionTok{cat}\NormalTok{(}\StringTok{"\textgreater{}\textgreater{} VERDICT: WIDE FORMAT (one row per hospital)}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{    \}}
    
    \CommentTok{\# Preview rows for a single hospital to show the repetition}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"\textgreater{}\textgreater{} Sample rows for ONE hospital (showing repetition pattern):}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{    sample\_id }\OtherTok{\textless{}{-}}\NormalTok{ df[[id\_col]][}\DecValTok{1}\NormalTok{]}
\NormalTok{    sample\_rows }\OtherTok{\textless{}{-}}\NormalTok{ df[df[[id\_col]] }\SpecialCharTok{==}\NormalTok{ sample\_id, ]}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"   Hospital ID:"}\NormalTok{, sample\_id, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"   Number of rows for this hospital:"}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(sample\_rows), }\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{print}\NormalTok{(}\FunctionTok{head}\NormalTok{(sample\_rows, }\DecValTok{5}\NormalTok{))}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\NormalTok{\}}

\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# Run inspection on both datasets}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# }\AlertTok{NOTE}\CommentTok{: Replace "FacilityId" below with the actual ID column name}
\CommentTok{\# if it\textquotesingle{}s different. Check names(HCAHPS) first to confirm.}

\FunctionTok{inspect\_df}\NormalTok{(HCAHPS, }
           \AttributeTok{df\_name =} \StringTok{"HCAHPS"}\NormalTok{, }
           \AttributeTok{id\_col  =} \StringTok{"FacilityId"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ============================================================
##   Dataset: HCAHPS 
## ============================================================
## 
## >> Dimensions (rows x columns):
##    Rows:     325,856 
##    Columns:  22 
## 
## >> Column names:
##  [1] "FacilityId"                        "FacilityName"                     
##  [3] "Address"                           "CityTown"                         
##  [5] "State"                             "ZipCode"                          
##  [7] "CountyParish"                      "TelephoneNumber"                  
##  [9] "HcahpsMeasureId"                   "HcahpsQuestion"                   
## [11] "HcahpsAnswerDescription"           "PatientSurveyStarRating"          
## [13] "PatientSurveyStarRatingFootnote"   "HcahpsAnswerPercent"              
## [15] "HcahpsAnswerPercentFootnote"       "HcahpsLinearMeanValue"            
## [17] "NumberOfCompletedSurveys"          "NumberOfCompletedSurveysFootnote" 
## [19] "SurveyResponseRatePercent"         "SurveyResponseRatePercentFootnote"
## [21] "StartDate"                         "EndDate"                          
## 
## >> Unique hospitals vs total rows:
##    Unique hospitals (FacilityId): 4,792
##    Total rows:                    325,856
##    Avg rows per hospital:         68
## 
## >> VERDICT: LONG FORMAT detected
##    Each hospital appears in ~68 rows on average.
##    This is a dimensionality issue — data needs to be
##    pivoted to WIDE format for one-row-per-hospital analysis.
## 
## >> Sample rows for ONE hospital (showing repetition pattern):
##    Hospital ID: 010001 
##    Number of rows for this hospital: 68 
## 
## # A tibble: 5 x 22
##   FacilityId FacilityName            Address CityTown State ZipCode CountyParish
##   <chr>      <chr>                   <chr>   <chr>    <chr> <chr>   <chr>       
## 1 010001     SOUTHEAST HEALTH MEDIC~ 1108 R~ DOTHAN   AL    36301   HOUSTON     
## 2 010001     SOUTHEAST HEALTH MEDIC~ 1108 R~ DOTHAN   AL    36301   HOUSTON     
## 3 010001     SOUTHEAST HEALTH MEDIC~ 1108 R~ DOTHAN   AL    36301   HOUSTON     
## 4 010001     SOUTHEAST HEALTH MEDIC~ 1108 R~ DOTHAN   AL    36301   HOUSTON     
## 5 010001     SOUTHEAST HEALTH MEDIC~ 1108 R~ DOTHAN   AL    36301   HOUSTON     
## # i 15 more variables: TelephoneNumber <chr>, HcahpsMeasureId <chr>,
## #   HcahpsQuestion <chr>, HcahpsAnswerDescription <chr>,
## #   PatientSurveyStarRating <chr>, PatientSurveyStarRatingFootnote <dbl>,
## #   HcahpsAnswerPercent <chr>, HcahpsAnswerPercentFootnote <chr>,
## #   HcahpsLinearMeanValue <chr>, NumberOfCompletedSurveys <chr>,
## #   NumberOfCompletedSurveysFootnote <chr>, SurveyResponseRatePercent <chr>,
## #   SurveyResponseRatePercentFootnote <chr>, StartDate <chr>, EndDate <chr>
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{inspect\_df}\NormalTok{(FY\_2026\_Hospital\_Readmissions\_Reduction\_Program, }
           \AttributeTok{df\_name =} \StringTok{"FY\_2026\_Hospital\_Readmissions\_Reduction\_Program"}\NormalTok{, }
           \AttributeTok{id\_col  =} \StringTok{"FacilityId"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ============================================================
##   Dataset: FY_2026_Hospital_Readmissions_Reduction_Program 
## ============================================================
## 
## >> Dimensions (rows x columns):
##    Rows:     18,330 
##    Columns:  12 
## 
## >> Column names:
##  [1] "FacilityName"             "FacilityId"              
##  [3] "State"                    "MeasureName"             
##  [5] "NumberOfDischarges"       "Footnote"                
##  [7] "ExcessReadmissionRatio"   "PredictedReadmissionRate"
##  [9] "ExpectedReadmissionRate"  "NumberOfReadmissions"    
## [11] "StartDate"                "EndDate"                 
## 
## >> Unique hospitals vs total rows:
##    Unique hospitals (FacilityId): 3,055
##    Total rows:                    18,330
##    Avg rows per hospital:         6
## 
## >> VERDICT: LONG FORMAT detected
##    Each hospital appears in ~6 rows on average.
##    This is a dimensionality issue — data needs to be
##    pivoted to WIDE format for one-row-per-hospital analysis.
## 
## >> Sample rows for ONE hospital (showing repetition pattern):
##    Hospital ID: 010001 
##    Number of rows for this hospital: 6 
## 
## # A tibble: 5 x 12
##   FacilityName          FacilityId State MeasureName NumberOfDischarges Footnote
##   <chr>                 <chr>      <chr> <chr>       <chr>                 <dbl>
## 1 SOUTHEAST HEALTH MED~ 010001     AL    READM-30-H~ N/A                      NA
## 2 SOUTHEAST HEALTH MED~ 010001     AL    READM-30-C~ 137                      NA
## 3 SOUTHEAST HEALTH MED~ 010001     AL    READM-30-A~ 273                      NA
## 4 SOUTHEAST HEALTH MED~ 010001     AL    READM-30-C~ 122                      NA
## 5 SOUTHEAST HEALTH MED~ 010001     AL    READM-30-P~ 507                      NA
## # i 6 more variables: ExcessReadmissionRatio <chr>,
## #   PredictedReadmissionRate <chr>, ExpectedReadmissionRate <chr>,
## #   NumberOfReadmissions <chr>, StartDate <chr>, EndDate <chr>
\end{verbatim}

\subsubsection{Tidy the data response variables' dataframe: Fiscal Year
2026 Hospital Readmissions Reduction
Program.}\label{tidy-the-data-response-variables-dataframe-fiscal-year-2026-hospital-readmissions-reduction-program.}

We are going to focus on the dataset
\texttt{FY\_2026\_Hospital\_Readmissions\_Reduction\_Program} to work on
best practices to
\href{https://vita.had.co.nz/papers/tidy-data.pdf}{tidy our data}.
Although I do not personally choose to follow everything that Hadley
Wickham and the \textbf{Tidy Data} Movement has espoused, I do think a
lot of the best practices are useful principles especially when we are
just getting use to working with data. Further, we can leverage a lot of
the functions to make our lives MUCH easier! And who doesn't like
easier?!

\subparagraph{\texorpdfstring{\textbf{Question 3}: {[}1
point{]}}{Question 3: {[}1 point{]}}}\label{question-3-1-point}

Take a deeper look at
\texttt{FY\_2026\_Hospital\_Readmissions\_Reduction\_Program} at some of
the numeric variables in the dataset, e.g.,
\texttt{NumberOfReadmissions}?

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hrrp\_2026 }\OtherTok{\textless{}{-}}\NormalTok{ FY\_2026\_Hospital\_Readmissions\_Reduction\_Program}

\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# Step 1: Check the column names and current data types}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}

\FunctionTok{tibble}\NormalTok{(}
    \StringTok{\textasciigrave{}}\AttributeTok{\#}\StringTok{\textasciigrave{}}      \OtherTok{=} \FunctionTok{seq\_along}\NormalTok{(hrrp\_2026),}
    \AttributeTok{Column   =} \FunctionTok{names}\NormalTok{(hrrp\_2026),}
    \AttributeTok{Class    =} \FunctionTok{sapply}\NormalTok{(hrrp\_2026, class)}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{Expected =} \FunctionTok{case\_when}\NormalTok{(}
            \StringTok{\textasciigrave{}}\AttributeTok{\#}\StringTok{\textasciigrave{}} \SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{7}\SpecialCharTok{:}\DecValTok{10}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \StringTok{"numeric"}\NormalTok{,}
            \StringTok{\textasciigrave{}}\AttributeTok{\#}\StringTok{\textasciigrave{}} \SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\DecValTok{11}\NormalTok{, }\DecValTok{12}\NormalTok{)  }\SpecialCharTok{\textasciitilde{}} \StringTok{"date"}\NormalTok{,}
            \ConstantTok{TRUE}                \SpecialCharTok{\textasciitilde{}} \StringTok{"character"}
\NormalTok{        ),}
        \AttributeTok{Issue =} \FunctionTok{ifelse}\NormalTok{(Class }\SpecialCharTok{!=}\NormalTok{ Expected, }\StringTok{"⚠️ NEEDS FIX"}\NormalTok{, }\StringTok{"✓ OK"}\NormalTok{)}
\NormalTok{    ) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{print}\NormalTok{(}\AttributeTok{n =} \ConstantTok{Inf}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 12 x 5
##      `#` Column                   Class     Expected  Issue      
##    <int> <chr>                    <chr>     <chr>     <chr>      
##  1     1 FacilityName             character character ✓ OK       
##  2     2 FacilityId               character character ✓ OK       
##  3     3 State                    character character ✓ OK       
##  4     4 MeasureName              character character ✓ OK       
##  5     5 NumberOfDischarges       character numeric   ⚠️ NEEDS FIX
##  6     6 Footnote                 numeric   character ⚠️ NEEDS FIX
##  7     7 ExcessReadmissionRatio   character numeric   ⚠️ NEEDS FIX
##  8     8 PredictedReadmissionRate character numeric   ⚠️ NEEDS FIX
##  9     9 ExpectedReadmissionRate  character numeric   ⚠️ NEEDS FIX
## 10    10 NumberOfReadmissions     character numeric   ⚠️ NEEDS FIX
## 11    11 StartDate                character date      ⚠️ NEEDS FIX
## 12    12 EndDate                  character date      ⚠️ NEEDS FIX
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# These columns SHOULD be numeric but are stored as character}
\NormalTok{problem\_cols }\OtherTok{\textless{}{-}} \FunctionTok{names}\NormalTok{(hrrp\_2026)[}\FunctionTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{7}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)]}

\CommentTok{\# Build a summary table of non{-}numeric values in each problem column}
\NormalTok{non\_numeric\_summary }\OtherTok{\textless{}{-}} \FunctionTok{map\_dfr}\NormalTok{(problem\_cols, }\ControlFlowTok{function}\NormalTok{(col) \{}
\NormalTok{    values }\OtherTok{\textless{}{-}}\NormalTok{ hrrp\_2026[[col]]}
\NormalTok{    non\_numeric }\OtherTok{\textless{}{-}}\NormalTok{ values[}\FunctionTok{is.na}\NormalTok{(}\FunctionTok{suppressWarnings}\NormalTok{(}\FunctionTok{as.numeric}\NormalTok{(values)))]}
    
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{length}\NormalTok{(non\_numeric) }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
        \FunctionTok{return}\NormalTok{(}\FunctionTok{tibble}\NormalTok{(}\AttributeTok{Column =}\NormalTok{ col, }\AttributeTok{NonNumericValue =} \StringTok{"(none)"}\NormalTok{, }\AttributeTok{Count =} \DecValTok{0}\NormalTok{))}
\NormalTok{    \}}
    
    \FunctionTok{as\_tibble}\NormalTok{(}\FunctionTok{table}\NormalTok{(non\_numeric)) }\SpecialCharTok{\%\textgreater{}\%}
        \FunctionTok{rename}\NormalTok{(}\AttributeTok{NonNumericValue =}\NormalTok{ non\_numeric, }\AttributeTok{Count =}\NormalTok{ n) }\SpecialCharTok{\%\textgreater{}\%}
        \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Column =}\NormalTok{ col, }\AttributeTok{.before =} \DecValTok{1}\NormalTok{)}
\NormalTok{\})}

\NormalTok{non\_numeric\_summary}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 6 x 3
##   Column                   NonNumericValue   Count
##   <chr>                    <chr>             <int>
## 1 NumberOfDischarges       N/A               10088
## 2 ExcessReadmissionRatio   N/A                6610
## 3 PredictedReadmissionRate N/A                6610
## 4 ExpectedReadmissionRate  N/A                6610
## 5 NumberOfReadmissions     N/A                6610
## 6 NumberOfReadmissions     Too Few to Report  3683
\end{verbatim}

\textbf{Hint: }Columns 5 \& 7:10 have problems with the \texttt{NA}
class.

\subparagraph{\texorpdfstring{\textbf{Question 4}: {[}1
point{]}}{Question 4: {[}1 point{]}}}\label{question-4-1-point}

Investigate the \texttt{replace\_with\_na\_all()} function that is part
of the \texttt{naniar} package. Use this function to fix the \texttt{NA}
class in the aberrant columns in
\texttt{FY\_2026\_Hospital\_Readmissions\_Reduction\_Program}.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hrrp\_2026 }\OtherTok{\textless{}{-}}\NormalTok{ FY\_2026\_Hospital\_Readmissions\_Reduction\_Program}

\CommentTok{\# Replace "N/A" and "Too Few to Report" strings with real NA values}
\NormalTok{hrrp\_2026\_clean }\OtherTok{\textless{}{-}}\NormalTok{ hrrp\_2026 }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{replace\_with\_na\_all}\NormalTok{(}
        \AttributeTok{condition =} \SpecialCharTok{\textasciitilde{}}\NormalTok{ .x }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"N/A"}\NormalTok{, }\StringTok{"Too Few to Report"}\NormalTok{)}
\NormalTok{    )}
\end{Highlighting}
\end{Shaded}

You will notice that this aberrant class of missing value
\textbf{caused} the numeric columns to be coerced into character columns
when they were imported by \texttt{read\_csv()}. Although we could try
using \texttt{as.numeric()} by itself, which would assign \texttt{NA} to
any non-numeric entry in
\texttt{FY\_2024\_Hospital\_Readmissions\_Reduction\_Program}, the
problem is that we could lose important information that way. Thus, as
annoying as this is, we should fix it a little more specifically\ldots{}

\subparagraph{\texorpdfstring{\textbf{Question 5}: {[}1
point{]}}{Question 5: {[}1 point{]}}}\label{question-5-1-point}

Look more closely at the \texttt{NumberOfReadmissions} column in the
\texttt{FY\_2026\_Hospital\_Readmissions\_Reduction\_Program}. What
other issue do you see with this specific column that is coercing it to
the character type, and why does it exist?

\textbf{Hint: } Make sure to use the accompanying data dictionary
\textbf{HOSPITAL\_Data\_Dictionary.pdf} to also examine \textbf{WHY}
this problem exists!

\textbf{Answer:} Beyond the ``N/A'' values shared with other numeric
columns, NumberOfReadmissions uniquely contains ``Too Few to Report''
(3,683 rows), which is what additionally coerces it to character type.
on page 97 in \textbf{HOSPITAL\_Data\_Dictionary.pdf}, Footnote \#1,
regarding The number of cases/patients is too few to report, the reason
is: • When the number of cases/patients does not meet the required
minimum amount for public reporting; • When the number of cases/patients
is too small to reliably tell how a facility is performing; and/or • To
protect personal health information.

Which show NumberOfReadmissions is the only column that's literally
counting individual patients. That's the one that creates privacy risk
if it's small. The other columns are either totals (like
NumberOfDischarges) or statistical calculations (like
ExcessReadmissionRatio), which don't directly point to individual
patients. Looking at the actual data, the smallest published readmission
count is 11, meaning CMS hides any value below that threshold to prevent
reidentification of specific patients.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Full cross{-}tabulation}
\NormalTok{FY\_2026\_Hospital\_Readmissions\_Reduction\_Program }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{count}\NormalTok{(NumberOfReadmissions, Footnote, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{head}\NormalTok{(}\DecValTok{15}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 15 x 3
##    NumberOfReadmissions Footnote     n
##    <chr>                   <dbl> <int>
##  1 Too Few to Report          NA  3545
##  2 N/A                         5  3255
##  3 N/A                         1  3150
##  4 11                         NA   301
##  5 14                         NA   283
##  6 12                         NA   257
##  7 15                         NA   237
##  8 13                         NA   227
##  9 17                         NA   215
## 10 N/A                         7   205
## 11 16                         NA   204
## 12 19                         NA   204
## 13 18                         NA   203
## 14 21                         NA   195
## 15 23                         NA   180
\end{verbatim}

\subparagraph{\texorpdfstring{\textbf{Question 6}: {[}1
point{]}}{Question 6: {[}1 point{]}}}\label{question-6-1-point}

Investigate the \texttt{gsub()} function that is part of base \texttt{R}
or any other function of your choosing. Use the function you choose to
\textbf{replace} the problematic text in the
\texttt{NumberOfReadmissions} column in
\texttt{FY\_2024\_Hospital\_Readmissions\_Reduction\_Program} with a
\textbf{5}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Replace "Too Few to Report" with 5 in NumberOfReadmissions}
\NormalTok{hrrp\_2026 }\OtherTok{\textless{}{-}}\NormalTok{ FY\_2026\_Hospital\_Readmissions\_Reduction\_Program }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{NumberOfReadmissions =} \FunctionTok{gsub}\NormalTok{(}\StringTok{"Too Few to Report"}\NormalTok{, }\StringTok{"5"}\NormalTok{, NumberOfReadmissions))}

\CommentTok{\# Verify the replacement worked}
\NormalTok{hrrp\_2026 }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{count}\NormalTok{(NumberOfReadmissions, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{head}\NormalTok{(}\DecValTok{10}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 10 x 2
##    NumberOfReadmissions     n
##    <chr>                <int>
##  1 N/A                   6610
##  2 5                     3683
##  3 11                     318
##  4 14                     290
##  5 12                     263
##  6 15                     243
##  7 13                     236
##  8 17                     218
##  9 18                     213
## 10 19                     213
\end{verbatim}

\subparagraph{\texorpdfstring{\textbf{Question 7}: {[}1
point{]}}{Question 7: {[}1 point{]}}}\label{question-7-1-point}

Speculate as to why I asked you to replace the text with a \textbf{5}
rather than a \textbf{0} or an \texttt{NA}. Can you think of any other
logical choices for the substitution? Do you agree with my choice?
(You're free to disagree, but please defend your decision either way!)

\textbf{Answer:} The choice of 5 is a midpoint imputation. based on
above my analysis suppressess count below 11, the true hidden value
falls between 0 and 10, and 5 is the midpoint of that range ---
basically the best single guess when we don't know anything more
specific about each hospital. 0 would be wrong because we know these
hospitals did have readmissions (otherwise they'd be reported as 0 with
no need for suppression). Using 0 would unfairly make small hospitals
look like they had perfect outcomes. NA would seem more honest, but it
throws away useful information (we do know the value is between 1 and
10) and would make these rows indistinguishable from the ``N/A'' rows
that represent a totally different missingness reason --- hospitals that
weren't measured at all.

I agree with using 5. It's the least biased single-point estimate, keeps
the row usable for analysis, and preserves the distinction from the
``N/A'' rows. For a real study I'd probably add a flag column to track
which values were imputed, but for this tidying step, 5 is a solid
choice.

\subparagraph{\texorpdfstring{\textbf{Question 8}: {[}1
point{]}}{Question 8: {[}1 point{]}}}\label{question-8-1-point}

Now, imagine an alternative scenario where instead of replacing it with
a \textbf{5}, I instead asked you to replace it with a randomly sampled
integer from 1 to 10. What would this do? Would \texttt{gsub()} work
here or would I need to execute it a different way, e.g., with an
\texttt{lapply()} function or a \texttt{for()} loop?

\textbf{Answer:} Random sampling would assign each of the 3,683
suppressed rows its own independent random integer from 1--10, rather
than all sharing the same value (5). This preserves more realistic
variance in the column.

gsub() would not work here, We need something that processes the column
element-by-element so a fresh random value is generated for each row. A
for() loop would work, and ifelse() with a vectorized sample(1:10, size
= n(), replace = TRUE) would also work (and would be faster)

\subparagraph{\texorpdfstring{\textbf{Question 9}: {[}3
points{]}}{Question 9: {[}3 points{]}}}\label{question-9-3-points}

You probably anticipated this! We just decided that, rather than a
\textbf{5} we want a randomly sampled integer from 1 to 10.

\textbf{Hint 1: } You might find it easier to read the data in from
fresh and, after commenting out your \texttt{gsub} from Question 5,
pattern match on the problematic text.

\textbf{Hint 2: } This is NOT the only way to do this, but I solved this
using \texttt{gregexpr()}, \texttt{regmatches()}, and \texttt{lapply()}.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# decide read file again before clean up }
\NormalTok{hrrp\_2026 }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}
    \FunctionTok{paste0}\NormalTok{(filepath, }\StringTok{"FY\_2026\_Hospital\_Readmissions\_Reduction\_Program\_Hospital.csv"}\NormalTok{),}
    \AttributeTok{show\_col\_types =} \ConstantTok{FALSE}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{clean\_names}\NormalTok{(}\AttributeTok{case =} \StringTok{"upper\_camel"}\NormalTok{)}

\FunctionTok{set.seed}\NormalTok{(}\DecValTok{123}\NormalTok{)}

\CommentTok{\# Step 1: Use gregexpr() to find positions of "Too Few to Report" in each cell}
\NormalTok{matches }\OtherTok{\textless{}{-}} \FunctionTok{gregexpr}\NormalTok{(}\StringTok{"Too Few to Report"}\NormalTok{, hrrp\_2026}\SpecialCharTok{$}\NormalTok{NumberOfReadmissions)}

\CommentTok{\# Step 2: Use lapply() to generate a random integer (1{-}10) for each match}
\CommentTok{\# Each list element gets its own random value}
\NormalTok{replacements }\OtherTok{\textless{}{-}} \FunctionTok{lapply}\NormalTok{(matches, }\ControlFlowTok{function}\NormalTok{(m) \{}
    \CommentTok{\# m is a vector of match positions for one cell}
    \CommentTok{\# If the cell has a match (position != {-}1), generate ONE random integer per match}
    \CommentTok{\# If no match, return an empty character vector}
    \ControlFlowTok{if}\NormalTok{ (m[}\DecValTok{1}\NormalTok{] }\SpecialCharTok{==} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{) \{}
        \FunctionTok{character}\NormalTok{(}\DecValTok{0}\NormalTok{)}
\NormalTok{    \} }\ControlFlowTok{else}\NormalTok{ \{}
        \FunctionTok{as.character}\NormalTok{(}\FunctionTok{sample}\NormalTok{(}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{, }\FunctionTok{length}\NormalTok{(m), }\AttributeTok{replace =} \ConstantTok{TRUE}\NormalTok{))}
\NormalTok{    \}}
\NormalTok{\})}

\CommentTok{\# Step 3: Use regmatches() \textless{}{-} to inject the replacements back into the column}
\FunctionTok{regmatches}\NormalTok{(hrrp\_2026}\SpecialCharTok{$}\NormalTok{NumberOfReadmissions, matches) }\OtherTok{\textless{}{-}}\NormalTok{ replacements}

\CommentTok{\# Verify the result}
\NormalTok{hrrp\_2026 }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{count}\NormalTok{(NumberOfReadmissions, }\AttributeTok{sort =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{head}\NormalTok{(}\DecValTok{15}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## # A tibble: 15 x 2
##    NumberOfReadmissions     n
##    <chr>                <int>
##  1 N/A                   6610
##  2 10                     394
##  3 2                      391
##  4 8                      372
##  5 7                      371
##  6 9                      365
##  7 1                      364
##  8 3                      363
##  9 4                      360
## 10 5                      356
## 11 6                      347
## 12 11                     318
## 13 14                     290
## 14 12                     263
## 15 15                     243
\end{verbatim}

\subparagraph{\texorpdfstring{\textbf{Question 10}: {[}1
point{]}}{Question 10: {[}1 point{]}}}\label{question-10-1-point}

It is finally time to fix those aberrant character columns by making
them numeric. However, just using \texttt{as.numeric()} would require us
to do it over and over on each of the columns in multiple lines of code.
Instead, investigate the function \texttt{mutate\_at()} which will allow
you to pass it a list of columns you want to convert with the function
you want to use.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Use mutate\_at() to convert all aberrant character columns to numeric at once}
\NormalTok{hrrp\_2026 }\OtherTok{\textless{}{-}}\NormalTok{ hrrp\_2026 }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate\_at}\NormalTok{(}
        \FunctionTok{vars}\NormalTok{(NumberOfDischarges, ExcessReadmissionRatio, }
\NormalTok{             PredictedReadmissionRate, ExpectedReadmissionRate, }
\NormalTok{             NumberOfReadmissions),}
\NormalTok{        as.numeric}
\NormalTok{    )}

\CommentTok{\# Verify all five columns are now numeric}
\FunctionTok{sapply}\NormalTok{(hrrp\_2026[, }\FunctionTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{7}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)], class)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##       NumberOfDischarges   ExcessReadmissionRatio PredictedReadmissionRate 
##                "numeric"                "numeric"                "numeric" 
##  ExpectedReadmissionRate     NumberOfReadmissions 
##                "numeric"                "numeric"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Confirm math operations work now}
\FunctionTok{summary}\NormalTok{(hrrp\_2026[, }\FunctionTok{c}\NormalTok{(}\DecValTok{5}\NormalTok{, }\DecValTok{7}\SpecialCharTok{:}\DecValTok{10}\NormalTok{)])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  NumberOfDischarges ExcessReadmissionRatio PredictedReadmissionRate
##  Min.   :   0.0     Min.   :0.470          Min.   : 1.908          
##  1st Qu.: 117.0     1st Qu.:0.958          1st Qu.:12.530          
##  Median : 198.0     Median :0.997          Median :15.860          
##  Mean   : 283.4     Mean   :1.002          Mean   :14.981          
##  3rd Qu.: 358.0     3rd Qu.:1.042          3rd Qu.:18.419          
##  Max.   :3672.0     Max.   :1.630          Max.   :28.164          
##  NA's   :10088      NA's   :6610           NA's   :6610            
##  ExpectedReadmissionRate NumberOfReadmissions
##  Min.   : 3.088          Min.   :  1.00      
##  1st Qu.:12.624          1st Qu.:  9.00      
##  Median :15.857          Median : 19.00      
##  Mean   :14.948          Mean   : 35.17      
##  3rd Qu.:18.501          3rd Qu.: 44.00      
##  Max.   :26.865          Max.   :847.00      
##  NA's   :6610            NA's   :6610
\end{verbatim}

\paragraph{Let's look more closely at Measure
Names.}\label{lets-look-more-closely-at-measure-names.}

Notice, that what I have done here first is used the \texttt{gsub()}
function to \texttt{mutate()} the \texttt{MeasureName} column to remove
the text that flanked the medical conditions.

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hrrp\_2026 }\OtherTok{\textless{}{-}}\NormalTok{  hrrp\_2026 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{MeasureName =} \FunctionTok{gsub}\NormalTok{(}\StringTok{"READM{-}30{-}"}\NormalTok{, }\StringTok{""}\NormalTok{, MeasureName)) }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{MeasureName =} \FunctionTok{gsub}\NormalTok{(}\StringTok{"{-}HRRP"}\NormalTok{, }\StringTok{""}\NormalTok{, MeasureName)) }

\FunctionTok{unique}\NormalTok{(hrrp\_2026}\SpecialCharTok{$}\NormalTok{MeasureName)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "HIP-KNEE" "CABG"     "AMI"      "COPD"     "PN"       "HF"
\end{verbatim}

\textbf{Note:} If at this point you've had any issues with any of the
previous problems 2-10, you can load the cleaned readmissions data,
\texttt{readmissionsClean.Rdata} so that you can proceed with the
assignment.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\AttributeTok{file =} \StringTok{"readmissionsClean.Rdata"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subparagraph{\texorpdfstring{\textbf{Question 11}: {[}1
point{]}}{Question 11: {[}1 point{]}}}\label{question-11-1-point}

Investigate the function \texttt{pivot\_wider()} or \texttt{spread()}
from the \texttt{tidyr} package, which comes bundled with
\texttt{tidyverse}. Try pivoting the
\texttt{FY\_2024\_Hospital\_Readmissions\_Reduction\_Program} dataset
wider. Make sure you correctly identify the \texttt{names\_from} and
\texttt{values\_from} column(s). \textbf{Make sure to save it as a
separate dataframe called \texttt{wideDF}.} Use the \texttt{dim()}
function to prove to me that you successfully pivoted wider.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Your code here.}
\NormalTok{wideDF }\OtherTok{\textless{}{-}}\NormalTok{ hrrp\_2026 }\SpecialCharTok{\%\textgreater{}\%}
  \FunctionTok{pivot\_wider}\NormalTok{(}
    \AttributeTok{id\_cols =} \FunctionTok{c}\NormalTok{(FacilityName, FacilityId, State),}
    \AttributeTok{names\_from =}\NormalTok{ MeasureName,}
    \AttributeTok{values\_from =} \FunctionTok{c}\NormalTok{(NumberOfDischarges, ExcessReadmissionRatio,}
\NormalTok{                    PredictedReadmissionRate, ExpectedReadmissionRate,}
\NormalTok{                    NumberOfReadmissions)}
\NormalTok{  )}

\CommentTok{\# Prove the pivot worked}
\FunctionTok{dim}\NormalTok{(wideDF)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3055   33
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(wideDF)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "FacilityName"                      "FacilityId"                       
##  [3] "State"                             "NumberOfDischarges_HIP-KNEE"      
##  [5] "NumberOfDischarges_CABG"           "NumberOfDischarges_AMI"           
##  [7] "NumberOfDischarges_COPD"           "NumberOfDischarges_PN"            
##  [9] "NumberOfDischarges_HF"             "ExcessReadmissionRatio_HIP-KNEE"  
## [11] "ExcessReadmissionRatio_CABG"       "ExcessReadmissionRatio_AMI"       
## [13] "ExcessReadmissionRatio_COPD"       "ExcessReadmissionRatio_PN"        
## [15] "ExcessReadmissionRatio_HF"         "PredictedReadmissionRate_HIP-KNEE"
## [17] "PredictedReadmissionRate_CABG"     "PredictedReadmissionRate_AMI"     
## [19] "PredictedReadmissionRate_COPD"     "PredictedReadmissionRate_PN"      
## [21] "PredictedReadmissionRate_HF"       "ExpectedReadmissionRate_HIP-KNEE" 
## [23] "ExpectedReadmissionRate_CABG"      "ExpectedReadmissionRate_AMI"      
## [25] "ExpectedReadmissionRate_COPD"      "ExpectedReadmissionRate_PN"       
## [27] "ExpectedReadmissionRate_HF"        "NumberOfReadmissions_HIP-KNEE"    
## [29] "NumberOfReadmissions_CABG"         "NumberOfReadmissions_AMI"         
## [31] "NumberOfReadmissions_COPD"         "NumberOfReadmissions_PN"          
## [33] "NumberOfReadmissions_HF"
\end{verbatim}

\subsubsection{Filtering for specific
conditions.}\label{filtering-for-specific-conditions.}

Ideally, though, before we'd pivot wider we would decide if we were
going to filter for any specific hospital readmission conditions. For
your \textbf{Project 1}, you will be choosing which medical condition(s)
you want to focus on for predicting hospital readmission. However, for
the remainder of this demo, we're going to focus on just
\textbf{pneumonia}.

\textbf{Ideas you might consider for your Project\_1 are:}

\begin{itemize}
\tightlist
\item
  surgical interventions (\texttt{HIP-KNEE}, \texttt{CABG})
\item
  heart-related conditions (\texttt{HF}, \texttt{AMI}, \& \texttt{CABG})
\item
  all conditions (warning: this might be too unwieldy!)
\item
  any other condition(s) that you motivate with a statement or two in
  support
\end{itemize}

Therefore, let's filter for just pneumonia-related readmissions which
will actually eliminate the need to pivot wider in just this case
(because we only chose a single condition).

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# filter}
\NormalTok{readmissionsClean }\OtherTok{\textless{}{-}} 
\NormalTok{  hrrp\_2026 }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{filter}\NormalTok{(MeasureName }\SpecialCharTok{==} \StringTok{"PN"}\NormalTok{)}

\FunctionTok{dim}\NormalTok{(readmissionsClean)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 3055   12
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{unique}\NormalTok{(readmissionsClean}\SpecialCharTok{$}\NormalTok{MeasureName)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "PN"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Verify One row per hospital}
\FunctionTok{nrow}\NormalTok{(readmissionsClean) }\SpecialCharTok{==} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(readmissionsClean}\SpecialCharTok{$}\NormalTok{FacilityId))}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] TRUE
\end{verbatim}

Table 2. Acronyms of medical conditions for which hospital readmissions
are tracked.

Acronym

Definition

HIP-KNEE

Total Hip/Knee Arthroplasty

HF

Heart Failure

COPD

Chronic Obstructive Pulmonary Disease

AMI

Acute Myocardial Infarction

CABG

Coronary Artery Bypass Graft

PN

Pneumonia

It's important to understand that these medical conditions are the
\textbf{ones that Medicaid/Medicare tracks for hospital readmissions}.
These are not the only conditions in which a patient might be
readmitted, but these are the ones that the agency uses to keep track of
hospital performance.

\subsubsection{Dynamic creation of merged dataframe objects: supporting
dataframes.}\label{dynamic-creation-of-merged-dataframe-objects-supporting-dataframes.}

We will often be asked to deal with large, unwieldy datasets and
sometimes we need to be able to handle them dynamically. \textbf{Dynamic
variable assignment}, as I demonstrated when we read in the files, is
going to come in handy - but it can sometimes be tricky to accomplish.
The whole point, though, is to create code that can handle ANYTHING you
throw at it.

In a similar vein, we can also perform \textbf{dynamic dataframe
creation} when we need to modify and stitch together more than one
pre-existing dataframe - ESPECIALLY when we might decide down the line
to alter our choices by adding or removing other dataframes.

\paragraph{Writing your own function to create objects
dynamically.}\label{writing-your-own-function-to-create-objects-dynamically.}

We are going to take all the cleaning steps we did above that was not
specific to the
\texttt{FY\_2026\_Hospital\_Readmissions\_Reduction\_Program} dataframe
and tidy, pivot, \& filter for specific readmission conditions, and
iteratively join as many dataframes as needed. The goal is to make
something flexible enough that, if you change a set of inputs, it will
create a joined table from ANY set of dataframe inputs. There is more
than one way to do this; but leveraging some of the existing
\texttt{tidyverse} and \texttt{tidyr} functions will likely help you
make this very flexible. Please note, however, that you do not have to
use those packages.

I start you out with something I find helpful when joining together
dataframes that sometimes have \emph{redundant} columns BUT not every
column is in every dataframe. I start by making a dataframe called
\texttt{hospitalInfo} that contains the pertinent information on each
hospital in the dataset, so you can drop those columns from the other
dataframes to prevent inflation or issues when you later join the
dataframes together. You may want to join each of the other dataframes
to \texttt{hospitalInfo}.

As I was writing my own version of this function, I found that the
\texttt{Payment\ and\ Value\ of\ Care} table must be separated into two
tables to join well, at least with how I wrote my function. So, I do
that for you below. I also clean up \texttt{HCAHPS} to make it easier to
work for the function I wrote, so it may also be useful for you. Note
that what I'm doing in these cases is making sure that
\texttt{MeasureName} is the title of the column \textbf{I will join my
tables on.} In this way, I'm using the \texttt{MeasureName} as the
\textbf{key} for my table joins.

\textbf{First, make sure to separate the Payment and Values tables,
giving each facility IDs:}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{if}\NormalTok{ (}\FunctionTok{exists}\NormalTok{(}\StringTok{"Payment\_and\_Value\_of\_Care"}\NormalTok{)) \{}
\NormalTok{  paymentOnly }\OtherTok{\textless{}{-}}\NormalTok{ Payment\_and\_Value\_of\_Care }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{select}\NormalTok{(FacilityId, PaymentMeasureName, PaymentCategory, Payment) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Payment =} \FunctionTok{gsub}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{$"}\NormalTok{, }\StringTok{""}\NormalTok{, Payment)) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Remove the dollar sign}
    \FunctionTok{mutate}\NormalTok{(}\AttributeTok{Payment =} \FunctionTok{gsub}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}\textbackslash{}}\StringTok{,"}\NormalTok{, }\StringTok{""}\NormalTok{, Payment)) }\SpecialCharTok{\%\textgreater{}\%} \CommentTok{\# Remove the comma }
    \FunctionTok{rename}\NormalTok{(}\AttributeTok{MeasureName =}\NormalTok{ PaymentMeasureName)  }\CommentTok{\# Make consistent with other tables}
  
\NormalTok{  valueOnly }\OtherTok{\textless{}{-}}\NormalTok{ Payment\_and\_Value\_of\_Care }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{select}\NormalTok{(FacilityId, ValueOfCareDisplayName, ValueOfCareCategory) }\SpecialCharTok{\%\textgreater{}\%} 
    \FunctionTok{rename}\NormalTok{(}\AttributeTok{MeasureName =}\NormalTok{ ValueOfCareDisplayName)  }\CommentTok{\# Make consistent with other tables}
\NormalTok{\} }\ControlFlowTok{else}\NormalTok{ \{}
  \FunctionTok{print}\NormalTok{(}\StringTok{"Payment\_and\_Value\_of\_Care table not available."}\NormalTok{)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] "Payment_and_Value_of_Care table not available."
\end{verbatim}

\textbf{HCAHPS is also a mess. Remove the columns that we will never use
in any analysis, make a \texttt{MeasureName} column, and also drop the
'' - linear mean score'' from some rows in the newly minted
\texttt{MeasureName}}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{HCAHPS }\OtherTok{\textless{}{-}} \FunctionTok{read\_csv}\NormalTok{(}
    \FunctionTok{paste0}\NormalTok{(filepath, }\StringTok{"HCAHPS{-}Hospital.csv"}\NormalTok{),}
    \AttributeTok{show\_col\_types =} \ConstantTok{FALSE}
\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{clean\_names}\NormalTok{(}\AttributeTok{case =} \StringTok{"upper\_camel"}\NormalTok{)}

\NormalTok{HCAHPS\_clean }\OtherTok{\textless{}{-}}\NormalTok{ HCAHPS }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{HcahpsMeasureId, }\SpecialCharTok{{-}}\NormalTok{PatientSurveyStarRatingFootnote, }
         \SpecialCharTok{{-}}\NormalTok{HcahpsAnswerPercentFootnote, }\SpecialCharTok{{-}}\NormalTok{NumberOfCompletedSurveysFootnote,}
         \SpecialCharTok{{-}}\NormalTok{SurveyResponseRatePercentFootnote, }\SpecialCharTok{{-}}\NormalTok{HcahpsAnswerDescription,}
         \SpecialCharTok{{-}}\NormalTok{PatientSurveyStarRating) }\SpecialCharTok{\%\textgreater{}\%}  \DocumentationTok{\#\# Drops the columns we don\textquotesingle{}t need}
  \FunctionTok{rename}\NormalTok{(}\AttributeTok{MeasureName =}\NormalTok{ HcahpsQuestion) }\SpecialCharTok{\%\textgreater{}\%}  \DocumentationTok{\#\# Makes a new MeasureName column}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{MeasureName =} \FunctionTok{gsub}\NormalTok{(}\StringTok{" {-} linear mean score"}\NormalTok{, }\StringTok{""}\NormalTok{, MeasureName))}
\DocumentationTok{\#\# Takes off the phrase that we don\textquotesingle{}t want}

\FunctionTok{names}\NormalTok{(HCAHPS\_clean)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "FacilityId"                "FacilityName"             
##  [3] "Address"                   "CityTown"                 
##  [5] "State"                     "ZipCode"                  
##  [7] "CountyParish"              "TelephoneNumber"          
##  [9] "MeasureName"               "HcahpsAnswerPercent"      
## [11] "HcahpsLinearMeanValue"     "NumberOfCompletedSurveys" 
## [13] "SurveyResponseRatePercent" "StartDate"                
## [15] "EndDate"
\end{verbatim}

\textbf{Lastly, pull the hospital information off of the Payment and
Value table because it is complete there. We can then drop this
information from all the other tables:}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{hospitalInfo }\OtherTok{\textless{}{-}}\NormalTok{ HCAHPS\_clean }\SpecialCharTok{\%\textgreater{}\%} 
              \DocumentationTok{\#\# Information about the hospitals}
                \FunctionTok{select}\NormalTok{(FacilityId, FacilityName, Address, CityTown, }
\NormalTok{                         State, ZipCode, CountyParish, TelephoneNumber) }\SpecialCharTok{\%\textgreater{}\%}
                \FunctionTok{distinct}\NormalTok{()}


\NormalTok{n\_unique }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(hospitalInfo}\SpecialCharTok{$}\NormalTok{FacilityId))}
    
\FunctionTok{cat}\NormalTok{(}\StringTok{"   Rows:            "}\NormalTok{, }\FunctionTok{format}\NormalTok{(}\FunctionTok{nrow}\NormalTok{(hospitalInfo), }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Rows:             4,792
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"   Unique hospitals:"}\NormalTok{, }\FunctionTok{format}\NormalTok{(n\_unique, }\AttributeTok{big.mark =} \StringTok{","}\NormalTok{), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Unique hospitals: 4,792
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"   Columns:         "}\NormalTok{, }\FunctionTok{ncol}\NormalTok{(hospitalInfo), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##    Columns:          8
\end{verbatim}

\subparagraph{\texorpdfstring{\textbf{Question 12}: {[}5
points{]}}{Question 12: {[}5 points{]}}}\label{question-12-5-points}

Write a function that will:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\item
  Fix any issues identified previously, e.g., issues with the
  \texttt{NA} class or pivoting, if needed
\item
  Join any number of a list of dataframes you give it. For example, it
  should be able to join these 8 tables:
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{datList }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(Healthcare\_Associated\_Infections,}
                \CommentTok{\#paymentOnly,  \# skiled {-}{-} not exist in files}
\NormalTok{                Outpatient\_Imaging\_Efficiency,}
\NormalTok{                Complications\_and\_Deaths,}
\NormalTok{                Medicare\_Hospital\_Spending\_Per\_Patient, }
\NormalTok{                Timely\_and\_Effective\_Care, }
\NormalTok{                Unplanned\_Hospital\_Visits,}
\NormalTok{                HCAHPS\_clean)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{2}
\tightlist
\item
  Filters the data for given criteria and condition(s) prior to
  pivoting. For example, for the 8 tables listed above, perhaps to
  filter for these possible measures before pivoting, so that I'm not
  pivoting ALL of those measures! (That would likely crash R!). Notice
  that what we're filtering for - is really a selection criteria, but
  because the data are in \textbf{wide format}, we are selecting them by
  row (i.e., ``filter'') rather than selection by column (i.e.,
  ``select'').
\end{enumerate}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{filterList }\OtherTok{\textless{}{-}} \FunctionTok{list}\NormalTok{(}\StringTok{"MRSA Bacteremia"}\NormalTok{, }
                   \StringTok{"Abdomen CT Use of Contrast Material"}\NormalTok{, }
                   
                   \FunctionTok{c}\NormalTok{(}\StringTok{"Death rate for pneumonia patients"}\NormalTok{, }
                     \StringTok{"Perioperative pulmonary embolism or deep vein thrombosis rate"}\NormalTok{,}
                     \StringTok{"CMS Medicare PSI 90: Patient safety and adverse events composite"}\NormalTok{, }
                     \StringTok{"Postoperative respiratory failure rate"}\NormalTok{),}
                   
                   \StringTok{"Medicare hospital spending per patient (Medicare Spending per Beneficiary)"}\NormalTok{,}
                   
                   \FunctionTok{c}\NormalTok{(}\StringTok{"Healthcare workers given influenza vaccination"}\NormalTok{, }
                     \StringTok{"Percentage of healthcare personnel who completed COVID{-}19 primary vaccination series"}\NormalTok{, }
                     \StringTok{"Average (median) time patients spent in the emergency department before leaving from the visit A lower number of minutes is better"}\NormalTok{, }
                     \StringTok{"Left before being seen"}\NormalTok{,}
                     \StringTok{"Venous Thromboembolism Prophylaxis"}\NormalTok{, }
                     \StringTok{"Intensive Care Unit Venous Thromboembolism Prophylaxis"}\NormalTok{, }
                     \StringTok{"Emergency department volume"}\NormalTok{),}
                   
                   \StringTok{"Hospital return days for pneumonia patients"}\NormalTok{,}
                   
                   \FunctionTok{c}\NormalTok{(}\StringTok{"Nurse communication"}\NormalTok{,}
                     \StringTok{"Doctor communication"}\NormalTok{,}
                     \StringTok{"Staff responsiveness"}\NormalTok{,}
                     \StringTok{"Communication about medicines"}\NormalTok{,}
                     \StringTok{"Discharge information"}\NormalTok{,}
                     \StringTok{"Care transition"}\NormalTok{,}
                     \StringTok{"Cleanliness"}\NormalTok{,}
                     \StringTok{"Quietness"}\NormalTok{,}
                     \StringTok{"Overall hospital rating"}\NormalTok{,}
                     \StringTok{"Recommend hospital"}\NormalTok{)}
\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{3}
\tightlist
\item
  For full credit, make sure that your function can clean up and join
  together at least three of the dataframes. \textbf{Note}: Make sure to
  join with \texttt{readmissionsClean} at the end!
\end{enumerate}

Perhaps you will choose to start your function like this (although you
do not have to):

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tidyNjoin }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(datList, filterList, hospitalInfo) \{}

\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{itemize}
\item
  \textbf{Hint 1: } Feel free to drop the \texttt{startDate} and
  \texttt{endDate} columns, as well as the \texttt{footnote} column. I
  would even suggest dropping \texttt{MeasureId}.
\item
  \textbf{Hint 2: } \texttt{select(-any\_of(c(...)))} can be used to
  drop any of a list of columns, regardless of whether it exists in
  every dataframe or not.
\item
  \textbf{Hint 3: } If you choose to drop all those extraneous columns,
  then the column you will need to merge/join on will always be in the
  second position, \texttt{MeasureName}.
\item
  \textbf{Hint 4: } \texttt{full\_join()} in \texttt{dplyr} is likely
  what you will need; you will want to execute the join on
  \texttt{FacilityId}.
\item
  \textbf{Hint 5: } Make sure to check for and/or remove duplicate rows.
\item
  \textbf{Hint 6: } Write \textbf{\emph{pseudocode}}, which is using
  English to write out our programming logic. Then, use that pseudocode
  to have generative AI help you craft the function. Make sure to test
  it well! GenAI is often very wrong!
\item
  \textbf{Hint 6: } If you are really stuck, move ahead and I give you a
  cleaned, merged data set to work with.
\end{itemize}

Okay, take a stab at it!

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{tidyNjoin }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(datList, filterList, hospitalInfo) \{}
  
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
  \CommentTok{\# Helper: clean one dataframe with its matching filter}
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{  clean\_one }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(df, filter\_vals) \{}
    
      \CommentTok{\# Safety check: must be a dataframe}
      \ControlFlowTok{if}\NormalTok{ (}\SpecialCharTok{!}\FunctionTok{is.data.frame}\NormalTok{(df)) \{}
            \FunctionTok{warning}\NormalTok{(}\StringTok{"Input is not a dataframe (class: "}\NormalTok{, }\FunctionTok{class}\NormalTok{(df)[}\DecValTok{1}\NormalTok{], }\StringTok{")"}\NormalTok{)}
            \FunctionTok{return}\NormalTok{(}\ConstantTok{NULL}\NormalTok{)}
\NormalTok{      \}}
        
  
    \CommentTok{\# Step 1: Drop unwanted columns (based on Hint 1\&2)}
    \CommentTok{\# any\_of() handles cases where a column doesn\textquotesingle{}t exist in every df}
\NormalTok{    df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
      \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{any\_of}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"StartDate"}\NormalTok{, }\StringTok{"EndDate"}\NormalTok{, }\StringTok{"Footnote"}\NormalTok{, }\StringTok{"MeasureId"}\NormalTok{,}
                       \StringTok{"FacilityName"}\NormalTok{, }\StringTok{"Address"}\NormalTok{, }\StringTok{"CityTown"}\NormalTok{, }\StringTok{"City"}\NormalTok{,}
                       \StringTok{"State"}\NormalTok{, }\StringTok{"ZipCode"}\NormalTok{, }\StringTok{"CountyParish"}\NormalTok{, }\StringTok{"Telephone"}\NormalTok{,}
                       \StringTok{"TelephoneNumber"}\NormalTok{, }\StringTok{"County"}\NormalTok{)))}
    
   
\NormalTok{    measure\_col }\OtherTok{\textless{}{-}} \FunctionTok{intersect}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"MeasureName"}\NormalTok{), }\FunctionTok{names}\NormalTok{(df))[}\DecValTok{1}\NormalTok{]}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.na}\NormalTok{(measure\_col)) \{}
        \FunctionTok{warning}\NormalTok{(}\StringTok{"No measure column found. Available: "}\NormalTok{, }
                \FunctionTok{paste}\NormalTok{(}\FunctionTok{names}\NormalTok{(df), }\AttributeTok{collapse =} \StringTok{", "}\NormalTok{))}
        \FunctionTok{return}\NormalTok{(}\ConstantTok{NULL}\NormalTok{)}
\NormalTok{    \}}
    
    \CommentTok{\# Step 2: Find the MeasureName column}
\NormalTok{    df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{filter}\NormalTok{(.data[[measure\_col]] }\SpecialCharTok{\%in\%}\NormalTok{ filter\_vals)}
    
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{nrow}\NormalTok{(df) }\SpecialCharTok{==} \DecValTok{0}\NormalTok{) \{}
      \FunctionTok{warning}\NormalTok{(}\StringTok{"Filter matched 0 rows for measure column "}\NormalTok{, measure\_col)}
      \FunctionTok{return}\NormalTok{(}\ConstantTok{NULL}\NormalTok{)}
\NormalTok{    \}}
    
    
    \CommentTok{\# Step 3: Replace common hidden NA strings with real NA values}
\NormalTok{    df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
      \FunctionTok{replace\_with\_na\_all}\NormalTok{(}
        \AttributeTok{condition =} \SpecialCharTok{\textasciitilde{}}\NormalTok{ .x }\SpecialCharTok{\%in\%} \FunctionTok{c}\NormalTok{(}\StringTok{"Not Available"}\NormalTok{, }\StringTok{"Not Applicable"}\NormalTok{, }
                                \StringTok{"N/A"}\NormalTok{, }\StringTok{"NA"}\NormalTok{, }\StringTok{"Too Few to Report"}\NormalTok{, }
                                \StringTok{"Not Calculated"}\NormalTok{, }\StringTok{""}\NormalTok{)}
\NormalTok{      )}
    
    \CommentTok{\# Ste 4: Identify the score/value column for pivoting}
\NormalTok{    score\_col }\OtherTok{\textless{}{-}} \FunctionTok{intersect}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"Score"}\NormalTok{, }\StringTok{"Value"}\NormalTok{, }\StringTok{"Payment"}\NormalTok{, }\StringTok{"Rate"}\NormalTok{,}
                                  \StringTok{"PatientSurveyStarRating"}\NormalTok{, }\StringTok{"HcahpsAnswerPercent"}\NormalTok{,}
                                  \StringTok{"MeasureScore"}\NormalTok{), }\FunctionTok{names}\NormalTok{(df))[}\DecValTok{1}\NormalTok{]}
    
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.na}\NormalTok{(score\_col)) \{}
      \FunctionTok{warning}\NormalTok{(}\StringTok{"No score column found. Available: "}\NormalTok{, }
              \FunctionTok{paste}\NormalTok{(}\FunctionTok{names}\NormalTok{(df), }\AttributeTok{collapse =} \StringTok{", "}\NormalTok{))}
      \FunctionTok{return}\NormalTok{(}\ConstantTok{NULL}\NormalTok{)}
\NormalTok{    \}}
    
    \CommentTok{\# Step 5: Pivot wider — each measure becomes its own column}
\NormalTok{    df }\OtherTok{\textless{}{-}}\NormalTok{ df }\SpecialCharTok{\%\textgreater{}\%}
      \FunctionTok{pivot\_wider}\NormalTok{(}
        \AttributeTok{id\_cols     =}\NormalTok{ FacilityId,}
        \AttributeTok{names\_from  =} \FunctionTok{all\_of}\NormalTok{(measure\_col),}
        \AttributeTok{values\_from =} \FunctionTok{all\_of}\NormalTok{(score\_col),}
        \AttributeTok{values\_fn   =}\NormalTok{ first   }\CommentTok{\# if duplicates, take first value}
\NormalTok{      ) }\SpecialCharTok{\%\textgreater{}\%} 
      \FunctionTok{distinct}\NormalTok{()}
      
    \FunctionTok{return}\NormalTok{(df)}
\NormalTok{  \}}
    
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
  \CommentTok{\# Clean every dataframe}
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{  cleaned\_list }\OtherTok{\textless{}{-}}\NormalTok{ purrr}\SpecialCharTok{::}\FunctionTok{map2}\NormalTok{(datList, filterList, clean\_one)}
    
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
  \CommentTok{\# DIAGNOSTIC: show what each cleaned dataframe looks like}
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"=== Diagnostic: cleaned\_list contents ===}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \FunctionTok{seq\_along}\NormalTok{(cleaned\_list)) \{}
\NormalTok{    item }\OtherTok{\textless{}{-}}\NormalTok{ cleaned\_list[[i]]}
    \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.null}\NormalTok{(item)) \{}
      \FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"  [\%d] NULL — cleaning failed}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, i))}
\NormalTok{    \} }\ControlFlowTok{else} \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.data.frame}\NormalTok{(item)) \{}
      \FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"  [\%d] OK ✓  dim=\%dx\%d}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, }
\NormalTok{                  i, }\FunctionTok{nrow}\NormalTok{(item), }\FunctionTok{ncol}\NormalTok{(item)))}
\NormalTok{    \} }\ControlFlowTok{else}\NormalTok{ \{}
      \FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"  [\%d] WRONG TYPE: \%s}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, i, }\FunctionTok{class}\NormalTok{(item)[}\DecValTok{1}\NormalTok{]))}
\NormalTok{    \}}
\NormalTok{  \}}
  \FunctionTok{cat}\NormalTok{(}\StringTok{"==========================================}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
    
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
  \CommentTok{\# Join everything to hospitalInfo}
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{  result }\OtherTok{\textless{}{-}}\NormalTok{ hospitalInfo}
    
  \ControlFlowTok{for}\NormalTok{ (i }\ControlFlowTok{in} \FunctionTok{seq\_along}\NormalTok{(cleaned\_list)) \{}
\NormalTok{    df }\OtherTok{\textless{}{-}}\NormalTok{ cleaned\_list[[i]]}
      \ControlFlowTok{if}\NormalTok{ (}\FunctionTok{is.data.frame}\NormalTok{(df) }\SpecialCharTok{\&\&} \FunctionTok{nrow}\NormalTok{(df) }\SpecialCharTok{\textgreater{}} \DecValTok{0}\NormalTok{) \{}
\NormalTok{          result }\OtherTok{\textless{}{-}}\NormalTok{ dplyr}\SpecialCharTok{::}\FunctionTok{full\_join}\NormalTok{(result, df, }\AttributeTok{by =} \StringTok{"FacilityId"}\NormalTok{)}
          \FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"Joined [\%d] — result now \%d x \%d}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{,}
\NormalTok{                      i, }\FunctionTok{nrow}\NormalTok{(result), }\FunctionTok{ncol}\NormalTok{(result)))}
\NormalTok{      \} }\ControlFlowTok{else}\NormalTok{ \{}
          \FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"Skipped [\%d] — not a usable dataframe}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, i))}
\NormalTok{      \}}
\NormalTok{  \}}
    
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
  \CommentTok{\# Final dedup and return}
  \CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{  result }\OtherTok{\textless{}{-}}\NormalTok{ result }\SpecialCharTok{\%\textgreater{}\%} \FunctionTok{distinct}\NormalTok{()}
  \FunctionTok{cat}\NormalTok{(}\FunctionTok{sprintf}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{Final result: \%d rows x \%d columns}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{, }\FunctionTok{nrow}\NormalTok{(result), }\FunctionTok{ncol}\NormalTok{(result)))}
    
  \FunctionTok{return}\NormalTok{(result)}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 1: Clean up readmissionsClean to drop redundant/unwanted columns}
\NormalTok{readmissionsClean\_for\_join }\OtherTok{\textless{}{-}}\NormalTok{ readmissionsClean }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{any\_of}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"FacilityName"}\NormalTok{, }\StringTok{"State"}\NormalTok{, }\StringTok{"MeasureName"}\NormalTok{,}
                     \StringTok{"Footnote"}\NormalTok{, }\StringTok{"StartDate"}\NormalTok{, }\StringTok{"EndDate"}\NormalTok{)))}

\CommentTok{\# Run the function}
\NormalTok{mergedDF }\OtherTok{\textless{}{-}} \FunctionTok{tidyNjoin}\NormalTok{(datList, filterList, hospitalInfo)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## === Diagnostic: cleaned_list contents ===
##   [1] OK ✓  dim=4792x2
##   [2] OK ✓  dim=4628x2
##   [3] OK ✓  dim=4792x5
##   [4] OK ✓  dim=4628x2
##   [5] OK ✓  dim=4660x6
##   [6] OK ✓  dim=4792x2
##   [7] OK ✓  dim=4792x9
## ==========================================
## 
## Joined [1] — result now 4792 x 9
## Joined [2] — result now 4792 x 10
## Joined [3] — result now 4792 x 14
## Joined [4] — result now 4792 x 15
## Joined [5] — result now 4792 x 20
## Joined [6] — result now 4792 x 21
## Joined [7] — result now 4792 x 29
## 
## Final result: 4792 rows x 29 columns
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Join readmissionsClean (your response variable) at the very end}
\NormalTok{mergedDF }\OtherTok{\textless{}{-}}\NormalTok{ mergedDF }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{    dplyr}\SpecialCharTok{::}\FunctionTok{full\_join}\NormalTok{(readmissionsClean\_for\_join, }\AttributeTok{by =} \StringTok{"FacilityId"}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}
\NormalTok{    dplyr}\SpecialCharTok{::}\FunctionTok{distinct}\NormalTok{()}

\CommentTok{\# Verify}
\FunctionTok{dim}\NormalTok{(mergedDF)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4802   34
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{names}\NormalTok{(mergedDF)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "FacilityId"                                                                
##  [2] "FacilityName"                                                              
##  [3] "Address"                                                                   
##  [4] "CityTown"                                                                  
##  [5] "State"                                                                     
##  [6] "ZipCode"                                                                   
##  [7] "CountyParish"                                                              
##  [8] "TelephoneNumber"                                                           
##  [9] "MRSA Bacteremia"                                                           
## [10] "Abdomen CT Use of Contrast Material"                                       
## [11] "Death rate for pneumonia patients"                                         
## [12] "Postoperative respiratory failure rate"                                    
## [13] "Perioperative pulmonary embolism or deep vein thrombosis rate"             
## [14] "CMS Medicare PSI 90: Patient safety and adverse events composite"          
## [15] "Medicare hospital spending per patient (Medicare Spending per Beneficiary)"
## [16] "Emergency department volume"                                               
## [17] "Healthcare workers given influenza vaccination"                            
## [18] "Left before being seen"                                                    
## [19] "Venous Thromboembolism Prophylaxis"                                        
## [20] "Intensive Care Unit Venous Thromboembolism Prophylaxis"                    
## [21] "Hospital return days for pneumonia patients"                               
## [22] "Nurse communication"                                                       
## [23] "Doctor communication"                                                      
## [24] "Communication about medicines"                                             
## [25] "Discharge information"                                                     
## [26] "Cleanliness"                                                               
## [27] "Quietness"                                                                 
## [28] "Overall hospital rating"                                                   
## [29] "Recommend hospital"                                                        
## [30] "NumberOfDischarges"                                                        
## [31] "ExcessReadmissionRatio"                                                    
## [32] "PredictedReadmissionRate"                                                  
## [33] "ExpectedReadmissionRate"                                                   
## [34] "NumberOfReadmissions"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Save as RDS to preserve data types perfectly}
\FunctionTok{saveRDS}\NormalTok{(mergedDF, }\StringTok{"mergedDF\_pneumonia\_2026.rds"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subparagraph{\texorpdfstring{\textbf{Question 13}: {[}1
point{]}}{Question 13: {[}1 point{]}}}\label{question-13-1-point}

Why do you think I just made you work through this function?
(\textbf{Hint}: What are you going to be asked to do in Project 1?)

\textbf{Answer:} Technically this would be reusable data tidying
pipeline I could used for other project as well. For Project 1, I'm
going to be asked to predict hospital readmissions for one or more
medical conditions, which means I'll need to do:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  Pull in multiple raw CMS datasets (HCAHPS, infections, mortality,
  spending, process measures, etc.)
\item
  Clean each one --- fix NA class issues, drop unnecessary columns,
  handle suppressed values
\item
  Filter to the specific measures I care about for my chosen
  condition(s) before pivoting wider
\item
  Join all of them together on FacilityId into a single modeling-ready
  table
\item
  Possibly do this multiple times as I refine which predictors I want to
  include, or if I switch to a different condition like CABG or hip/knee
\end{enumerate}

With create tidyNjoin() as a reusable function I won't have to rewrite
all process from scrach. It's repetitive pattern we should pay attention
during our DS works, and create resusable functionality for reduce
repeat effort.

\subsubsection{The full, merged, tidied dataset for
pneumonia.}\label{the-full-merged-tidied-dataset-for-pneumonia.}

Please load if you are struggling to get a function that performs the
task or if you aren't sure if it does what's expected.

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"pneumoniaFull.Rdata"}\NormalTok{)}
\FunctionTok{dim}\NormalTok{(pneumoniaFull)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4816  100
\end{verbatim}

As I mentioned in Question 12, I ultimately chose to merge 8 of the
datasets together for this dataset, although I selectively filtered to
focus on my question: \textbf{Can we predict pneumonia-related hospital
readmissions based on factors that might indicate how well the hospital
is doing at diagnostics and disease prevention?}

Whew! Notice that this dataset currently has \textbf{100 features} and
\textbf{4,816 rows}. That's definitely too many features, so let's
perform some additional feature selection.

\textbf{Let's start by examining the ``big picture'' of what's in this
giant dataset}:

Table 3. List of hospital-level data sets chosen for the
pneumonia-related readmissions analysis.

Dataset

Information Used

Rationale

Healthcare\_Associated\_Infections

MRSA Bacteremia

Hospital-transmitted disease rate

Outpatient\_Imaging\_Efficiency

Abdomen CT Use of Contrast Material

Proxy for imaging ability to diagnose pneumonia appropriately

Complications\_and\_Deaths

Death rate for pneumonia patients

Complications\_and\_Deaths

Perioperative pulmonary embolism or deep vein thrombosis rate

Diagnostic ability of hospital

Complications\_and\_Deaths

CMS Medicare PSI 90: Patient safety and adverse events composite

General hospital safety

Complications\_and\_Deaths

Postoperative respiratory failure rate

General ability for respiratory diagnostics

Medicare\_Hospital\_Spending\_Per\_Patient

Score

Score rather than \$ amount

Timely\_and\_Effective\_Care

Healthcare workers given influenza vaccination

Likelihood of influenza transmission

Timely\_and\_Effective\_Care

\% healthcare personnel completed COVID-19 primary vaccination series

Likelihood of COVID-19 transmission

Timely\_and\_Effective\_Care

Average (median) minutes patients spent in the ED before leaving (lower
is better)

Proxy for overall effective diagnosis \& treatment

Timely\_and\_Effective\_Care

Left before being seen in ED

Proxy for overall effective diagnosis \& treatment

Timely\_and\_Effective\_Care

Venous Thromboembolism Prophylaxis

Diagnostic ability for another critical and silent disease

Timely\_and\_Effective\_Care

ICU Thromboembolism Prophylaxis

Diagnostic ability for another critical and silent disease

Timely\_and\_Effective\_Care

Emergency department volume

Proxy for how overwhelmed the hospital is

Unplanned\_Hospital\_Visits

Hospital return days for pneumonia patients

HCAHPS

Nurse communication

Overall rating as linear score

HCAHPS

Doctor communication

Overall rating as linear score

HCAHPS

Staff responsiveness

Overall rating as linear score

HCAHPS

Communication about medicines

Overall rating as linear score

HCAHPS

Discharge information

Overall rating as linear score

HCAHPS

Care transition

Overall rating as linear score

HCAHPS

Cleanliness

Overall rating as linear score

HCAHPS

Quietness

Overall rating as linear score

HCAHPS

Overall hospital rating

Overall rating as linear score

HCAHPS

Recommend hospital

Overall rating as linear score

\section{Pre-processing \& Feature Selection (Round
1)}\label{pre-processing-feature-selection-round-1}

\textbf{WARNING}: Typically we would do a lot of this work AFTER
splitting into a training and testing set. I'm not having you do that
today so that you can write code that will help you with your Project1.
Just be aware that this goes against the typical workflow a bit.

Feature selection can take many forms, from what we've already done
(choosing features relevant to our question) to culling non-informative
columns to using more machine-guided approaches. We're going to leverage
all types here.

Additionally, we are going to perform \textbf{encoding} to our
categorical variables. It will be important to perform encoding
\textbf{BEFORE} using automated methods for feature selection.

\subsection{Culling Features (and, yes, more
tidying!)}\label{culling-features-and-yes-more-tidying}

Although we ideally could just include these steps (and perhaps you
did!) in our tidying \& joining function from Question 12, I wanted to
make sure we talk about this explicitly.

\subparagraph{\texorpdfstring{\textbf{Question 14}: {[}1
point{]}}{Question 14: {[}1 point{]}}}\label{question-14-1-point}

Looking through the feature names, you probably notice names like
\texttt{LowerEstimate\_Death\ rate\ for\ pneumonia\ patients}. We do not
need the higher and lower estimates in this case; just the point
estimates. Use the \texttt{contains()} function to \textbf{drop} any
columns that contain \texttt{LowerEstimate} or \texttt{HigherEstimate}.
Let's also go ahead and drop any columns containing \texttt{Denominator}
and \texttt{HcahpsAnswerPercent} as well. How many features did you
drop?

\textbf{Answer:}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"pneumoniaFull.Rdata"}\NormalTok{)}
\FunctionTok{dim}\NormalTok{(pneumoniaFull)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4816  100
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Count columns BEFORE dropping}
\NormalTok{n\_before }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(pneumoniaFull)}

\CommentTok{\# Drop columns matching the unwanted patterns}
\NormalTok{pneumoniaFull }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaFull }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{contains}\NormalTok{(}\StringTok{"LowerEstimate"}\NormalTok{),}
           \SpecialCharTok{{-}}\FunctionTok{contains}\NormalTok{(}\StringTok{"HigherEstimate"}\NormalTok{),}
           \SpecialCharTok{{-}}\FunctionTok{contains}\NormalTok{(}\StringTok{"Denominator"}\NormalTok{),}
           \SpecialCharTok{{-}}\FunctionTok{contains}\NormalTok{(}\StringTok{"HcahpsAnswerPercent"}\NormalTok{))}

\CommentTok{\# Count columns AFTER dropping}
\NormalTok{n\_after }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(pneumoniaFull)}

\CommentTok{\# How many features were dropped?}
\NormalTok{n\_dropped }\OtherTok{\textless{}{-}}\NormalTok{ n\_before }\SpecialCharTok{{-}}\NormalTok{ n\_after}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Features dropped:"}\NormalTok{, n\_dropped, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Features dropped: 25
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Columns before:  "}\NormalTok{, n\_before, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Columns before:   100
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Columns after:   "}\NormalTok{, n\_after, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Columns after:    75
\end{verbatim}

\textbf{Note:} Please drop \texttt{FacilityName},
\texttt{TelephoneNumber}, \texttt{Address}, \& \texttt{CityTown} at this
stage as well, if they're still in your full dataset.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Count columns before}
\NormalTok{n\_before }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(pneumoniaFull)}

\CommentTok{\# Drop the unwanted identifier columns}
\NormalTok{pneumoniaFull }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaFull }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{any\_of}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"FacilityName"}\NormalTok{, }\StringTok{"TelephoneNumber"}\NormalTok{, }
                     \StringTok{"Address"}\NormalTok{, }\StringTok{"CityTown"}\NormalTok{)))}

\CommentTok{\# Verify}
\NormalTok{n\_after  }\OtherTok{\textless{}{-}} \FunctionTok{ncol}\NormalTok{(pneumoniaFull)}
\NormalTok{n\_dropped }\OtherTok{\textless{}{-}}\NormalTok{ n\_before }\SpecialCharTok{{-}}\NormalTok{ n\_after}

\FunctionTok{cat}\NormalTok{(}\StringTok{"Columns before:  "}\NormalTok{, n\_before, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Columns before:   75
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Columns after:   "}\NormalTok{, n\_after, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Columns after:    71
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Features dropped:"}\NormalTok{, n\_dropped, }\StringTok{"}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Features dropped: 4
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Confirm the columns are gone}
\FunctionTok{names}\NormalTok{(pneumoniaFull)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  [1] "FacilityId"                                                                                                                               
##  [2] "State"                                                                                                                                    
##  [3] "ZipCode"                                                                                                                                  
##  [4] "CountyParish"                                                                                                                             
##  [5] "ComparedToNational_MRSA Bacteremia"                                                                                                       
##  [6] "Score_MRSA Bacteremia"                                                                                                                    
##  [7] "PaymentCategory_Payment for pneumonia patients"                                                                                           
##  [8] "Payment_Payment for pneumonia patients"                                                                                                   
##  [9] "Score_Abdomen CT Use of Contrast Material"                                                                                                
## [10] "ComparedToNational_Death rate for pneumonia patients"                                                                                     
## [11] "ComparedToNational_Postoperative respiratory failure rate"                                                                                
## [12] "ComparedToNational_Perioperative pulmonary embolism or deep vein thrombosis rate"                                                         
## [13] "ComparedToNational_CMS Medicare PSI 90: Patient safety and adverse events composite"                                                      
## [14] "Score_Death rate for pneumonia patients"                                                                                                  
## [15] "Score_Postoperative respiratory failure rate"                                                                                             
## [16] "Score_Perioperative pulmonary embolism or deep vein thrombosis rate"                                                                      
## [17] "Score_CMS Medicare PSI 90: Patient safety and adverse events composite"                                                                   
## [18] "Score_Medicare spending per patient"                                                                                                      
## [19] "Score_Emergency department volume"                                                                                                        
## [20] "Score_Percentage of healthcare personnel who completed COVID-19 primary vaccination series"                                               
## [21] "Score_Healthcare workers given influenza vaccination"                                                                                     
## [22] "Score_Average (median) time patients spent in the emergency department before leaving from the visit A lower number of minutes is better" 
## [23] "Score_Left before being seen"                                                                                                             
## [24] "Score_Venous Thromboembolism Prophylaxis"                                                                                                 
## [25] "Score_Intensive Care Unit Venous Thromboembolism Prophylaxis"                                                                             
## [26] "Sample_Emergency department volume"                                                                                                       
## [27] "Sample_Percentage of healthcare personnel who completed COVID-19 primary vaccination series"                                              
## [28] "Sample_Healthcare workers given influenza vaccination"                                                                                    
## [29] "Sample_Average (median) time patients spent in the emergency department before leaving from the visit A lower number of minutes is better"
## [30] "Sample_Left before being seen"                                                                                                            
## [31] "Sample_Venous Thromboembolism Prophylaxis"                                                                                                
## [32] "Sample_Intensive Care Unit Venous Thromboembolism Prophylaxis"                                                                            
## [33] "ComparedToNational_Hospital return days for pneumonia patients"                                                                           
## [34] "Score_Hospital return days for pneumonia patients"                                                                                        
## [35] "NumberOfPatients_Hospital return days for pneumonia patients"                                                                             
## [36] "NumberOfPatientsReturned_Hospital return days for pneumonia patients"                                                                     
## [37] "HcahpsLinearMeanValue_Nurse communication"                                                                                                
## [38] "HcahpsLinearMeanValue_Doctor communication"                                                                                               
## [39] "HcahpsLinearMeanValue_Staff responsiveness"                                                                                               
## [40] "HcahpsLinearMeanValue_Communication about medicines"                                                                                      
## [41] "HcahpsLinearMeanValue_Discharge information"                                                                                              
## [42] "HcahpsLinearMeanValue_Care transition"                                                                                                    
## [43] "HcahpsLinearMeanValue_Cleanliness"                                                                                                        
## [44] "HcahpsLinearMeanValue_Quietness"                                                                                                          
## [45] "HcahpsLinearMeanValue_Overall hospital rating"                                                                                            
## [46] "HcahpsLinearMeanValue_Recommend hospital"                                                                                                 
## [47] "NumberOfCompletedSurveys_Nurse communication"                                                                                             
## [48] "NumberOfCompletedSurveys_Doctor communication"                                                                                            
## [49] "NumberOfCompletedSurveys_Staff responsiveness"                                                                                            
## [50] "NumberOfCompletedSurveys_Communication about medicines"                                                                                   
## [51] "NumberOfCompletedSurveys_Discharge information"                                                                                           
## [52] "NumberOfCompletedSurveys_Care transition"                                                                                                 
## [53] "NumberOfCompletedSurveys_Cleanliness"                                                                                                     
## [54] "NumberOfCompletedSurveys_Quietness"                                                                                                       
## [55] "NumberOfCompletedSurveys_Overall hospital rating"                                                                                         
## [56] "NumberOfCompletedSurveys_Recommend hospital"                                                                                              
## [57] "SurveyResponseRatePercent_Nurse communication"                                                                                            
## [58] "SurveyResponseRatePercent_Doctor communication"                                                                                           
## [59] "SurveyResponseRatePercent_Staff responsiveness"                                                                                           
## [60] "SurveyResponseRatePercent_Communication about medicines"                                                                                  
## [61] "SurveyResponseRatePercent_Discharge information"                                                                                          
## [62] "SurveyResponseRatePercent_Care transition"                                                                                                
## [63] "SurveyResponseRatePercent_Cleanliness"                                                                                                    
## [64] "SurveyResponseRatePercent_Quietness"                                                                                                      
## [65] "SurveyResponseRatePercent_Overall hospital rating"                                                                                        
## [66] "SurveyResponseRatePercent_Recommend hospital"                                                                                             
## [67] "NumberOfDischarges"                                                                                                                       
## [68] "ExcessReadmissionRatio"                                                                                                                   
## [69] "PredictedReadmissionRate"                                                                                                                 
## [70] "ExpectedReadmissionRate"                                                                                                                  
## [71] "NumberOfReadmissions"
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\DocumentationTok{\#\#head(pneumoniaFull)}
\end{Highlighting}
\end{Shaded}

\subsection{Encoding}\label{encoding}

\subsubsection{Mystery encoding! (Well, it won't be a mystery for
long.)}\label{mystery-encoding-well-it-wont-be-a-mystery-for-long.}

\subparagraph{\texorpdfstring{\textbf{Question 15}: {[}1
point{]}}{Question 15: {[}1 point{]}}}\label{question-15-1-point}

We need to perform encoding on all of the categorical columns,
ultimately. However, we will focus first on the columns that begin with
`\texttt{ComparedToNational\_}, e.g.,
\texttt{ComparedToNational\_Death\ rate\ for\ pneumonia\ patients}. What
kind of encoding should we perform on these columns? Why?

\textbf{Answer:} We should perform ordinal encoding on the
ComparedToNational\_* columns.These columns are ordinal categorical
variables --- they contain three values (``Worse than the National
Rate'', ``No Different than the National Rate'', ``Better than the
National Rate'') with a clear, meaningful ranking from worst to best
performance. Ordinal encoding preserves this ordering by mapping each
category to a number that reflects its rank

``Worse than the National Rate'' = 1 ``No Different than the National
Rate'' = 2 ``Better than the National Rate'' = 3

This way, models can directly use the rank information --- a hospital
with a 3 is meaningfully ``above'' a hospital with a 1.

\subparagraph{\texorpdfstring{\textbf{Question 16}: {[}1
point{]}}{Question 16: {[}1 point{]}}}\label{question-16-1-point}

What other column do we also need to perform this kind of encoding on?

\textbf{Answer:} PaymentCategory\_Payment for pneumonia patients, This
column contains ordinal categorical values with a clear hierarchy, just
like the ComparedToNational\_* columns:

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\tightlist
\item
  ``Less Than the National Average Payment'' = 1 (lowest)
\item
  ``No Different Than the National Average Payment'' = 2 (middle)
\item
  ``Greater Than the National Average Payment'' = 3 (highest)
\end{enumerate}

Payment categories have a meaningful rank order --- a hospital paying
less is meaningfully different from one paying more, and the direction
matters. Ordinal encoding preserves this ranking so that models can
learn that payment level indicates hospital resource/capability levels,
which may be associated with readmission rates.

\subparagraph{\texorpdfstring{\textbf{Question 17}: {[}3
points{]}}{Question 17: {[}3 points{]}}}\label{question-17-3-points}

You probably expected this - attempt to encode those columns the method
you selected. It's okay if you can only think of a way to brute-force
this for now; I will show you code to help you do it faster after the
assignment. :)

\begin{itemize}
\item
  \textbf{Hint 1: }You could use the \texttt{contains()} or
  \texttt{startsWith()} functions to help you quickly grab those columns
  so you can make the changes you want to make.
\item
  \textbf{Hint 2: }You may want to explore the \texttt{grepl()} function
  or regular expressions, as they can allow us to match in a ``fuzzy''
  way.
\item
  \textbf{Hint 3: }You may want to create a temporary dataframe that you
  execute the changes on and then replace the original columns from
  there. That way, you don't have to keep reloading the original data if
  you make mistakes!
\item
  \textbf{Hint 3: }For full credit, don't forget to double check that
  you managed to preserve all the data! The \texttt{table()} function is
  sufficient here.
\end{itemize}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 1: Make a temp dataframe (Hint 3 — work on a copy)}
\NormalTok{temp\_encoded }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaFull }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(}\FunctionTok{contains}\NormalTok{(}\StringTok{"ComparedToNational\_"}\NormalTok{))}

\CommentTok{\# Step 2: Define encoding that handles all 4 naming conventions}
\CommentTok{\#cat("=== Unique values across ComparedToNational columns ===\textbackslash{}n")}
\NormalTok{encode\_compared }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(x) \{}
\NormalTok{    dplyr}\SpecialCharTok{::}\FunctionTok{case\_when}\NormalTok{(}
        \CommentTok{\# "Worse" performance — captures: Worse/More Days}
        \FunctionTok{grepl}\NormalTok{(}\StringTok{"Worse"}\NormalTok{,     x, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{,}
        \FunctionTok{grepl}\NormalTok{(}\StringTok{"More Days"}\NormalTok{, x, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \DecValTok{1}\NormalTok{,}
        
        \CommentTok{\# "No different" / "Average" — middle tier}
        \FunctionTok{grepl}\NormalTok{(}\StringTok{"No Different"}\NormalTok{, x, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \DecValTok{2}\NormalTok{,}
        \FunctionTok{grepl}\NormalTok{(}\StringTok{"\^{}Average"}\NormalTok{,     x, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \DecValTok{2}\NormalTok{,}
        
        \CommentTok{\# "Better" performance — captures: Better/Fewer Days}
        \FunctionTok{grepl}\NormalTok{(}\StringTok{"Better"}\NormalTok{,     x, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \DecValTok{3}\NormalTok{,}
        \FunctionTok{grepl}\NormalTok{(}\StringTok{"Fewer Days"}\NormalTok{, x, }\AttributeTok{ignore.case =} \ConstantTok{TRUE}\NormalTok{) }\SpecialCharTok{\textasciitilde{}} \DecValTok{3}\NormalTok{,}
        
        \CommentTok{\# Everything else (including NA) stays NA}
        \AttributeTok{.default =} \ConstantTok{NA\_real\_}
\NormalTok{    )}
\NormalTok{\}}


\CommentTok{\# Step 4: Apply the encoding to all 6 columns at once}
\NormalTok{temp\_encoded }\OtherTok{\textless{}{-}}\NormalTok{ temp\_encoded }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{everything}\NormalTok{(), encode\_compared))}

\CommentTok{\# Step 5: VERIFY counts preserved before/after (Hint 4 — full credit step!)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{=== Verification: counts BEFORE vs AFTER encoding ===}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## === Verification: counts BEFORE vs AFTER encoding ===
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\ControlFlowTok{for}\NormalTok{ (col }\ControlFlowTok{in} \FunctionTok{names}\NormalTok{(temp\_encoded)) \{}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{{-}{-}{-}{-}{-} "}\NormalTok{, col, }\StringTok{" {-}{-}{-}{-}{-}}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"BEFORE:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{); }\FunctionTok{print}\NormalTok{(}\FunctionTok{table}\NormalTok{(pneumoniaFull[[col]], }\AttributeTok{useNA =} \StringTok{"ifany"}\NormalTok{))}
    \FunctionTok{cat}\NormalTok{(}\StringTok{"AFTER:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{);  }\FunctionTok{print}\NormalTok{(}\FunctionTok{table}\NormalTok{(temp\_encoded[[col]], }\AttributeTok{useNA =} \StringTok{"ifany"}\NormalTok{))}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## -----  ComparedToNational_MRSA Bacteremia  -----
## BEFORE:
## 
##   Better than the National Benchmark No Different than National Benchmark 
##                                  166                                 1517 
##    Worse than the National Benchmark                                 <NA> 
##                                   50                                 3083 
## AFTER:
## 
##    1    2    3 <NA> 
##   50 1517  166 3083 
## 
## -----  ComparedToNational_Death rate for pneumonia patients  -----
## BEFORE:
## 
##       Better Than the National Rate No Different Than the National Rate 
##                                 216                                3165 
##        Worse Than the National Rate                                <NA> 
##                                 133                                1302 
## AFTER:
## 
##    1    2    3 <NA> 
##  133 3165  216 1302 
## 
## -----  ComparedToNational_Postoperative respiratory failure rate  -----
## BEFORE:
## 
##       Better Than the National Rate No Different Than the National Rate 
##                                  57                                2435 
##        Worse Than the National Rate                                <NA> 
##                                 111                                2213 
## AFTER:
## 
##    1    2    3 <NA> 
##  111 2435   57 2213 
## 
## -----  ComparedToNational_Perioperative pulmonary embolism or deep vein thrombosis rate  -----
## BEFORE:
## 
##       Better Than the National Rate No Different Than the National Rate 
##                                  16                                2845 
##        Worse Than the National Rate                                <NA> 
##                                  74                                1881 
## AFTER:
## 
##    1    2    3 <NA> 
##   74 2845   16 1881 
## 
## -----  ComparedToNational_CMS Medicare PSI 90: Patient safety and adverse events composite  -----
## BEFORE:
## 
##       Better Than the National Value No Different Than the National Value 
##                                   77                                 2774 
##        Worse Than the National Value                                 <NA> 
##                                  160                                 1805 
## AFTER:
## 
##    1    2    3 <NA> 
##  160 2774   77 1805 
## 
## -----  ComparedToNational_Hospital return days for pneumonia patients  -----
## BEFORE:
## 
##            Average Days per 100 Discharges 
##                                       2285 
## Fewer Days Than Average per 100 Discharges 
##                                        402 
##  More Days Than Average per 100 Discharges 
##                                        827 
##                                       <NA> 
##                                       1302 
## AFTER:
## 
##    1    2    3 <NA> 
##  827 2285  402 1302
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Step 6: Replace the originals in pneumoniaFull}
\NormalTok{pneumoniaFull }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaFull }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{contains}\NormalTok{(}\StringTok{"ComparedToNational\_"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{bind\_cols}\NormalTok{(temp\_encoded)}

\CommentTok{\# Step 7: Confirm result is numeric}
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{=== Final result: encoded columns are now numeric ===}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## === Final result: encoded columns are now numeric ===
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pneumoniaFull }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(}\FunctionTok{contains}\NormalTok{(}\StringTok{"ComparedToNational\_"}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{summary}\NormalTok{()}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##  ComparedToNational_MRSA Bacteremia
##  Min.   :1.000                     
##  1st Qu.:2.000                     
##  Median :2.000                     
##  Mean   :2.067                     
##  3rd Qu.:2.000                     
##  Max.   :3.000                     
##  NA's   :3083                      
##  ComparedToNational_Death rate for pneumonia patients
##  Min.   :1.000                                       
##  1st Qu.:2.000                                       
##  Median :2.000                                       
##  Mean   :2.024                                       
##  3rd Qu.:2.000                                       
##  Max.   :3.000                                       
##  NA's   :1302                                        
##  ComparedToNational_Postoperative respiratory failure rate
##  Min.   :1.000                                            
##  1st Qu.:2.000                                            
##  Median :2.000                                            
##  Mean   :1.979                                            
##  3rd Qu.:2.000                                            
##  Max.   :3.000                                            
##  NA's   :2213                                             
##  ComparedToNational_Perioperative pulmonary embolism or deep vein thrombosis rate
##  Min.   :1.00                                                                    
##  1st Qu.:2.00                                                                    
##  Median :2.00                                                                    
##  Mean   :1.98                                                                    
##  3rd Qu.:2.00                                                                    
##  Max.   :3.00                                                                    
##  NA's   :1881                                                                    
##  ComparedToNational_CMS Medicare PSI 90: Patient safety and adverse events composite
##  Min.   :1.000                                                                      
##  1st Qu.:2.000                                                                      
##  Median :2.000                                                                      
##  Mean   :1.972                                                                      
##  3rd Qu.:2.000                                                                      
##  Max.   :3.000                                                                      
##  NA's   :1805                                                                       
##  ComparedToNational_Hospital return days for pneumonia patients
##  Min.   :1.000                                                 
##  1st Qu.:2.000                                                 
##  Median :2.000                                                 
##  Mean   :1.879                                                 
##  3rd Qu.:2.000                                                 
##  Max.   :3.000                                                 
##  NA's   :1302
\end{verbatim}

\textbf{Note}: If you struggled with Question 17, load the data below
and keep going:

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"pneumoniaFullEncoded.Rdata"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\subsubsection{Frequency encoding state and
county.}\label{frequency-encoding-state-and-county.}

We also decide that we want a way to try to preserve and analyze the
geographic information without causing terrible overfitting. So, we will
try to apply \textbf{frequency encoding} to those two categorical
columns.

\subparagraph{\texorpdfstring{\textbf{Question 18}: {[}1
points{]}}{Question 18: {[}1 points{]}}}\label{question-18-1-points}

Go through the \textbf{frequency encoding} code chunk below and comment
each line. What does it do? \emph{Make sure to comment why you think the
choice was made}, if appropriate.

Extra comments:

One subtle drawback of frequency encoding: two different categories with
the same count get the same encoded value. For example, if Wyoming and
Vermont both have 30 hospitals, they'd both encode to 30 --- the model
can't distinguish them anymore.

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# get encode dataframe from previous process}
\NormalTok{pneumoniaFullEncoded }\OtherTok{=}\NormalTok{ pneumoniaFull}

\CommentTok{\# Specify which columns we want to frequency{-}encode.}
\CommentTok{\# WHY THESE TWO: State (50 levels) and CountyParish (hundreds of levels) }
\CommentTok{\# are high{-}cardinality nominal categoricals — they have no natural order, }
\CommentTok{\# so ordinal encoding doesn\textquotesingle{}t apply.Frequency encoding is a clever compromise.}
\NormalTok{cols2encode }\OtherTok{\textless{}{-}} \FunctionTok{c}\NormalTok{(}\StringTok{"State"}\NormalTok{, }
               \StringTok{"CountyParish"}\NormalTok{)}

\CommentTok{\# Extract just the columns we want to encode into a temporary dataframe.}
\CommentTok{\# WHY: working on a temp keeps the original safe and isolates the }
\CommentTok{\# operation — easier to debug, easier to verify before swapping back.}
\NormalTok{temp }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaFullEncoded[, }\FunctionTok{names}\NormalTok{(pneumoniaFullEncoded) }\SpecialCharTok{\%in\%}\NormalTok{ cols2encode]}

\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\CommentTok{\# HELPER FUNCTION: replace each category value with its frequency}
\CommentTok{\# {-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}{-}}
\NormalTok{add\_freq }\OtherTok{\textless{}{-}} \ControlFlowTok{function}\NormalTok{(data, column\_name) \{}
  
  \CommentTok{\# Build a frequency table: counts how many rows have each unique value.}
  \CommentTok{\# useNA = "always" includes NA as its own count, so missing values }
  \CommentTok{\# get a sensible encoded value too instead of silently disappearing.}
\NormalTok{  frequency\_map }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(data[[column\_name]], }\AttributeTok{useNA =} \StringTok{"always"}\NormalTok{)}
  
  \CommentTok{\# Replace each value in the column with its frequency count:}
  \CommentTok{\#   {-} names(frequency\_map)        → the unique category labels (e.g., "CA", "TX", "NY")}
  \CommentTok{\#   {-} match(data[[column]], ...)  → for each row, look up where its value }
  \CommentTok{\#                                   sits in the frequency\_map}
  \CommentTok{\#   {-} frequency\_map[match(...)]   → pull out the count for that value}
  \CommentTok{\# }
  \CommentTok{\# Example: if "California" appears 500 times, every row with State="California" }
  \CommentTok{\# becomes 500. If "Wyoming" appears 30 times, those rows become 30.}
  \CommentTok{\# WHY MATCH{-}BASED LOOKUP: this is vectorized — handles the whole column }
  \CommentTok{\# in one operation rather than looping row{-}by{-}row. Much faster on large data.}
  
\NormalTok{  data[[column\_name]] }\OtherTok{\textless{}{-}}\NormalTok{ frequency\_map[}\FunctionTok{match}\NormalTok{(data[[column\_name]],}
                                             \FunctionTok{names}\NormalTok{(frequency\_map))]}
  \FunctionTok{return}\NormalTok{(data)}
\NormalTok{\}}

\CommentTok{\# Loop through each column in temp and apply the frequency encoding.}
\CommentTok{\# WHY A LOOP: each call to add\_freq() builds a fresh frequency table }
\CommentTok{\# specific to that column (State counts ≠ County counts), so we can\textquotesingle{}t }
\CommentTok{\# vectorize across columns — each needs its own per{-}column table.}
\ControlFlowTok{for}\NormalTok{ (col }\ControlFlowTok{in} \FunctionTok{names}\NormalTok{(temp)) \{}
\NormalTok{  temp }\OtherTok{\textless{}{-}} \FunctionTok{add\_freq}\NormalTok{(temp, col)}
\NormalTok{\}}

\CommentTok{\# Copy the encoded columns from temp back into pneumoniaFullEncoded.}
\CommentTok{\# WHY USE A LOOP HERE: looping by name is explicit and safe — we\textquotesingle{}re }
\CommentTok{\# saying "replace exactly these columns with their encoded versions."}
\CommentTok{\# Using cols2encode[c] keeps the column names matched up so we don\textquotesingle{}t }
\CommentTok{\# accidentally write to the wrong column.}
\ControlFlowTok{for}\NormalTok{ (c }\ControlFlowTok{in} \DecValTok{1}\SpecialCharTok{:}\FunctionTok{length}\NormalTok{(cols2encode)) \{}
\NormalTok{  pneumoniaFullEncoded[, cols2encode[c]] }\OtherTok{\textless{}{-}}\NormalTok{ temp[, cols2encode[c]]}
\NormalTok{\}}
\end{Highlighting}
\end{Shaded}

\subparagraph{\texorpdfstring{\textbf{Question 19}: {[}1
point{]}}{Question 19: {[}1 point{]}}}\label{question-19-1-point}

Use your finally \& freshly encoded version of
\texttt{pneumoniaFullEncoded} to answer this vital question for
\texttt{State} and \texttt{CountyParish} features: are we justified
using these features? Why or why not? You will need to write code to
answer this question.

\textbf{Hint 1: }Use your original \texttt{pneumoniaFull} dataset to
compare the features in \texttt{pneumoniaFullEncoded}.

\textbf{Hint 2: } \textbf{Heavily} duplicated frequency values can make
it ill-advised to proceed with a frequency encoded feature. Low to
moderate duplication can be kept if there is a strong justification for
doing so.

\textbf{Hint 3: }If you decide it is ill-advised for either or both
columns, make sure to remove those features from the dataset!

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-} For STATE {-}{-}{-}}
\FunctionTok{cat}\NormalTok{(}\StringTok{"========================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ========================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"STATE feature evaluation}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## STATE feature evaluation
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"========================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ========================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# How many UNIQUE states existed in the original data?}
\NormalTok{n\_unique\_states }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFull}\SpecialCharTok{$}\NormalTok{State))}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Unique state categories (original):"}\NormalTok{, n\_unique\_states, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Unique state categories (original): 57
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# How many UNIQUE encoded values exist after frequency encoding?}
\NormalTok{n\_unique\_encoded\_state }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFullEncoded}\SpecialCharTok{$}\NormalTok{State))}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Unique encoded values (post{-}encoding):"}\NormalTok{, n\_unique\_encoded\_state, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Unique encoded values (post-encoding): 50
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# How much information was lost?}
\NormalTok{info\_loss\_state }\OtherTok{\textless{}{-}}\NormalTok{ n\_unique\_states }\SpecialCharTok{{-}}\NormalTok{ n\_unique\_encoded\_state}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Categories collapsed (info loss):"}\NormalTok{, info\_loss\_state, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Categories collapsed (info loss): 7
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Pct info preserved:"}\NormalTok{, }
    \FunctionTok{round}\NormalTok{(n\_unique\_encoded\_state }\SpecialCharTok{/}\NormalTok{ n\_unique\_states }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Pct info preserved: 87.7 %
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Show which states share the same frequency count}
\NormalTok{state\_freq\_table }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(pneumoniaFullEncoded}\SpecialCharTok{$}\NormalTok{State)}
\NormalTok{duplicates\_state }\OtherTok{\textless{}{-}}\NormalTok{ state\_freq\_table[state\_freq\_table }\SpecialCharTok{\textgreater{}} \DecValTok{1}\NormalTok{]}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Frequency values shared by multiple states:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Frequency values shared by multiple states:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(duplicates\_state)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   1   2   7  10  14  21  23  26  30  33  35  41  43  44  46  47  54  55  58  59 
##   2   4  14  10  14  21  23  52  30  33  35  41  43  44  92  47  54  55  58  59 
##  61  62  66  79  81  82  84  88  89  90  95  99 103 104 113 116 119 125 127 129 
##  61  62  66  79  81  82  84  88 178  90  95  99 103 104 226 116 119 125 127 129 
## 130 131 154 158 160 171 173 181 327 386 
## 130 131 154 158 160 171 173 181 327 386
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# {-}{-}{-} For COUNTYPARISH {-}{-}{-}}
\FunctionTok{cat}\NormalTok{(}\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{========================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
## ========================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"COUNTYPARISH feature evaluation}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## COUNTYPARISH feature evaluation
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"========================================}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## ========================================
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# How many UNIQUE counties existed in the original data?}
\NormalTok{n\_unique\_counties }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFull}\SpecialCharTok{$}\NormalTok{CountyParish))}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Unique county categories (original):"}\NormalTok{, n\_unique\_counties, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Unique county categories (original): 1549
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# How many UNIQUE encoded values exist after frequency encoding?}
\NormalTok{n\_unique\_encoded\_county }\OtherTok{\textless{}{-}} \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFullEncoded}\SpecialCharTok{$}\NormalTok{CountyParish))}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Unique encoded values (post{-}encoding):"}\NormalTok{, n\_unique\_encoded\_county, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Unique encoded values (post-encoding): 36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{info\_loss\_county }\OtherTok{\textless{}{-}}\NormalTok{ n\_unique\_counties }\SpecialCharTok{{-}}\NormalTok{ n\_unique\_encoded\_county}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Categories collapsed (info loss):"}\NormalTok{, info\_loss\_county, }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Categories collapsed (info loss): 1513
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"Pct info preserved:"}\NormalTok{,}
    \FunctionTok{round}\NormalTok{(n\_unique\_encoded\_county }\SpecialCharTok{/}\NormalTok{ n\_unique\_counties }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Pct info preserved: 2.3 %
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Show the distribution of frequency values}
\NormalTok{county\_freq\_table }\OtherTok{\textless{}{-}} \FunctionTok{table}\NormalTok{(pneumoniaFullEncoded}\SpecialCharTok{$}\NormalTok{CountyParish)}
\FunctionTok{cat}\NormalTok{(}\StringTok{"Top 10 most common frequency values for counties:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## Top 10 most common frequency values for counties:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{print}\NormalTok{(}\FunctionTok{sort}\NormalTok{(county\_freq\_table, }\AttributeTok{decreasing =} \ConstantTok{TRUE}\NormalTok{)[}\DecValTok{1}\SpecialCharTok{:}\DecValTok{10}\NormalTok{])}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##   1   2   4   3   6   5 171  11   8   7 
## 791 642 388 354 234 220 171 154 136 133
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# STATE}
\FunctionTok{cat}\NormalTok{(}\StringTok{"STATE:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## STATE:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Original unique categories:"}\NormalTok{, }\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFull}\SpecialCharTok{$}\NormalTok{State)), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Original unique categories: 57
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Encoded unique values:    "}\NormalTok{, }\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFullEncoded}\SpecialCharTok{$}\NormalTok{State)), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Encoded unique values:     50
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Info preserved:           "}\NormalTok{,}
    \FunctionTok{round}\NormalTok{(}\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFullEncoded}\SpecialCharTok{$}\NormalTok{State)) }\SpecialCharTok{/} 
          \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFull}\SpecialCharTok{$}\NormalTok{State)) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Info preserved:            87.7 %
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# COUNTYPARISH}
\FunctionTok{cat}\NormalTok{(}\StringTok{"COUNTYPARISH:}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## COUNTYPARISH:
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Original unique categories:"}\NormalTok{, }\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFull}\SpecialCharTok{$}\NormalTok{CountyParish)), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Original unique categories: 1549
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Encoded unique values:    "}\NormalTok{, }\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFullEncoded}\SpecialCharTok{$}\NormalTok{CountyParish)), }\StringTok{"}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Encoded unique values:     36
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{cat}\NormalTok{(}\StringTok{"  Info preserved:           "}\NormalTok{,}
    \FunctionTok{round}\NormalTok{(}\FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFullEncoded}\SpecialCharTok{$}\NormalTok{CountyParish)) }\SpecialCharTok{/} 
          \FunctionTok{length}\NormalTok{(}\FunctionTok{unique}\NormalTok{(pneumoniaFull}\SpecialCharTok{$}\NormalTok{CountyParish)) }\SpecialCharTok{*} \DecValTok{100}\NormalTok{, }\DecValTok{1}\NormalTok{), }\StringTok{"\%}\SpecialCharTok{\textbackslash{}n}\StringTok{"}\NormalTok{)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
##   Info preserved:            2.3 %
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Drop CountyParish since frequency encoding destroyed its information}
\NormalTok{pneumoniaFullEncoded }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaFullEncoded }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\NormalTok{CountyParish)}

\CommentTok{\# Verify it\textquotesingle{}s dropped}
\FunctionTok{dim}\NormalTok{(pneumoniaFullEncoded)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] 4816   70
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\StringTok{"CountyParish"} \SpecialCharTok{\%in\%} \FunctionTok{names}\NormalTok{(pneumoniaFullEncoded)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## [1] FALSE
\end{verbatim}

\textbf{Answer:} 1. STATE: JUSTIFIED --- KEEP. The state column had 57
unique categories, and frequency encoding preserved 50 unique encoded
values (87.7\% information retention). A few smaller states share
hospital counts and got collapsed together (e.g., 7 states sharing
low-count duplicate values), but most states remain distinguishable. The
frequency value itself carries meaningful signal --- hospital count per
state correlates with state population, urbanization, and healthcare
market size. This is low-to-moderate duplication with strong
justification, so we keep it.

\begin{enumerate}
\def\labelenumi{\arabic{enumi}.}
\setcounter{enumi}{1}
\tightlist
\item
  COUNTYPARISH: NOT JUSTIFIED --- DROP. This is a textbook example of
  when frequency encoding fails. The county column had 1,549 unique
  categories originally, but after encoding only 36 unique values remain
  --- a catastrophic 97.7\% information loss. The reason is structural:
  most US counties have only 1--3 hospitals each. The encoding collapsed
  791 different counties all to the value 1, another 642 counties to 2,
  388 counties to 4, and so on. A rural county in Montana and a rural
  county in Mississippi now look identical to any model. The vast
  majority of counties are indistinguishable from one another. Per Hint
  3, I removed this feature from the dataset.
\end{enumerate}

\subsubsection{Finishing touches}\label{finishing-touches}

\paragraph{1. Ensure that every feature is
numeric.}\label{ensure-that-every-feature-is-numeric.}

\begin{Shaded}
\begin{Highlighting}[]
\FunctionTok{load}\NormalTok{(}\StringTok{"pneumoniaAnalyze.Rdata"}\NormalTok{)}

\NormalTok{pneumoniaAnalyze }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaAnalyze }\SpecialCharTok{\%\textgreater{}\%} 
  \FunctionTok{mutate}\NormalTok{(}\FunctionTok{across}\NormalTok{(}\FunctionTok{where}\NormalTok{(is.character), as.numeric))}
\end{Highlighting}
\end{Shaded}

\paragraph{\texorpdfstring{2. Collapse the
\texttt{NumberOfCompletedSurveys\_}\ldots{} and
\texttt{SurveyResponseRatePercent\_}\ldots{} features into a single one,
as they are identical /
redundant:}{2. Collapse the NumberOfCompletedSurveys\_\ldots{} and SurveyResponseRatePercent\_\ldots{} features into a single one, as they are identical / redundant:}}\label{collapse-the-numberofcompletedsurveys_-and-surveyresponseratepercent_-features-into-a-single-one-as-they-are-identical-redundant}

\begin{Shaded}
\begin{Highlighting}[]
\NormalTok{pneumoniaAnalyze }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaAnalyze }\SpecialCharTok{\%\textgreater{}\%} 
  \DocumentationTok{\#\# arbitrarily chose as the rep as they are identical}
  \FunctionTok{mutate}\NormalTok{(}\AttributeTok{NumberSurveysCompleted =}\NormalTok{ NumberOfCompletedSurveys\_Cleanliness,              }
         \AttributeTok{SurveyResponseRate =}\NormalTok{ SurveyResponseRatePercent\_Cleanliness}\SpecialCharTok{/}\DecValTok{100}\NormalTok{) }\SpecialCharTok{\%\textgreater{}\%}       \DocumentationTok{\#\# Turned into an actual rate }
  \FunctionTok{select}\NormalTok{(}\SpecialCharTok{{-}}\FunctionTok{contains}\NormalTok{(}\FunctionTok{c}\NormalTok{(}\StringTok{"NumberOfCompletedSurveys\_"}\NormalTok{, }\StringTok{"SurveyResponseRatePercent\_"}\NormalTok{)))   }\DocumentationTok{\#\# drop the others}
\end{Highlighting}
\end{Shaded}

Excellent! Now we are down to just 51 features\ldots{}

\paragraph{3. Identify the target
variable.}\label{identify-the-target-variable.}

\textbf{Our very, very last steps!} Your task is to identify the
appropriate target variable from the dataset. I have purposefully not
gone into great detail about what it would be because choosing the best
target is sometimes tricky.

\subparagraph{\texorpdfstring{\textbf{Question 20}: {[}2
points{]}}{Question 20: {[}2 points{]}}}\label{question-20-2-points}

Use \texttt{pneumoniaAnalyze} to calculate an
\texttt{observed\_readmission\_rate} as the number of readmissions
divided by the number of discharges, multiplied by 100, then drop the
two columns used to make this new one. Now, using the data and the data
dictionary, try to understand the relationship between
\texttt{observed\_readmission\_rate} that we just created, the
\texttt{PredictedReadmissionRate}, \texttt{ExpectedReadmissionRate}, and
the \texttt{ExcessReadmissionRatio}. What is the relationship? What is
the appropriate target to choose and why?

\textbf{Hint: }Think about (or perhaps try to investigate) why the
\textbf{predicted} rate exists. What would be the (dis)advantage to
using the predicted vs.~the newly created
\texttt{observed\_readmission\_rate}?

\textbf{Answer:} The four variables are connected:
ExcessReadmissionRatio = PredictedReadmissionRate /
ExpectedReadmissionRate. The observed rate is just Readmissions /
Discharges. The appropriate target is ExcessReadmissionRatio because
it's the risk-adjusted, comparative measure of performance --- it
accounts for the fact that hospitals treating sicker patients would
naturally have higher raw readmission rates. CMS itself uses this for
the HRRP penalty calculations. Using the observed rate as a target would
unfairly penalize hospitals with complex patient populations, while the
predicted rate alone doesn't capture the comparison to expectations.

\subparagraph{\texorpdfstring{\textbf{Question 21}: {[}1
points{]}}{Question 21: {[}1 points{]}}}\label{question-21-1-points}

Why did I have you drop the two columns used to make
\texttt{observed\_readmission\_rate}?

\textbf{Answer:} Dropping NumberOfReadmissions and NumberOfDischarges
after computing observed\_readmission\_rate prevents target leakage
(also called data leakage). These two columns directly determine the
observed readmission rate by their ratio, so keeping them as predictors
would allow any model to perfectly reconstruct the response variable
just by dividing them. The model would appear to achieve near-perfect
accuracy, but it wouldn't be learning anything useful --- it would just
be doing arithmetic on the inputs to recreate the output.

\section{Exploratory Data Analysis}\label{exploratory-data-analysis}

For your final question, you will kick start our EDA by focusing on the
target variable that you identified in Question 20. \textbf{You will not
be penalized for choosing the wrong target as long as you made an
attempt to choose and defend a rational choice.}

\subparagraph{\texorpdfstring{\textbf{Question 22}: {[}3
points{]}}{Question 22: {[}3 points{]}}}\label{question-22-3-points}

Explore the target variable you identified in Question 20 with at least
one other variable. Try to push yourself to try a new style of plot; for
example, have you ever made a \texttt{density} or \texttt{violin} plot?
These can be excellent choices when exploring the distribution of a
target variable against another variable. Note that, if you choose to
compare the target against one of the encoded categorical variables, you
will need to properly re-label the categories for your plot.

Full points are awarded for professional plots with axis labels, labeled
legends (if appropriate), and creative use of multivariable information.
\textbf{One bonus point will be awarded if you make a faceted plot or
otherwise include information from at least 3 variables.}

Need inspiration that comes with code?!? Check out the
\href{https://r-graph-gallery.com}{R Graph Gallery}!

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Prepare data with the correct {-}1/0/1 encoding}
\NormalTok{plot\_data }\OtherTok{\textless{}{-}}\NormalTok{ pneumoniaAnalyze }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{filter}\NormalTok{(}\SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(ExcessReadmissionRatio),}
           \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{ComparedToNational\_Death rate for pneumonia patients}\StringTok{\textasciigrave{}}\NormalTok{),}
           \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{HcahpsLinearMeanValue\_Nurse communication}\StringTok{\textasciigrave{}}\NormalTok{),}
           \SpecialCharTok{!}\FunctionTok{is.na}\NormalTok{(}\StringTok{\textasciigrave{}}\AttributeTok{HcahpsLinearMeanValue\_Overall hospital rating}\StringTok{\textasciigrave{}}\NormalTok{)) }\SpecialCharTok{\%\textgreater{}\%}
    \FunctionTok{mutate}\NormalTok{(}
        \AttributeTok{DeathRateCategory =} \FunctionTok{case\_when}\NormalTok{(}
            \StringTok{\textasciigrave{}}\AttributeTok{ComparedToNational\_Death rate for pneumonia patients}\StringTok{\textasciigrave{}} \SpecialCharTok{==} \SpecialCharTok{{-}}\DecValTok{1} \SpecialCharTok{\textasciitilde{}} \StringTok{"Worse than National"}\NormalTok{,}
            \StringTok{\textasciigrave{}}\AttributeTok{ComparedToNational\_Death rate for pneumonia patients}\StringTok{\textasciigrave{}} \SpecialCharTok{==}  \DecValTok{0} \SpecialCharTok{\textasciitilde{}} \StringTok{"No Different"}\NormalTok{,}
            \StringTok{\textasciigrave{}}\AttributeTok{ComparedToNational\_Death rate for pneumonia patients}\StringTok{\textasciigrave{}} \SpecialCharTok{==}  \DecValTok{1} \SpecialCharTok{\textasciitilde{}} \StringTok{"Better than National"}
\NormalTok{        ),}
        \AttributeTok{DeathRateCategory =} \FunctionTok{factor}\NormalTok{(DeathRateCategory,}
                                   \AttributeTok{levels =} \FunctionTok{c}\NormalTok{(}\StringTok{"Worse than National"}\NormalTok{,}
                                              \StringTok{"No Different"}\NormalTok{,}
                                              \StringTok{"Better than National"}\NormalTok{))}
\NormalTok{    )}

\CommentTok{\# Verify all 3 categories appear}
\FunctionTok{table}\NormalTok{(plot\_data}\SpecialCharTok{$}\NormalTok{DeathRateCategory)}
\end{Highlighting}
\end{Shaded}

\begin{verbatim}
## 
##  Worse than National         No Different Better than National 
##                  123                 2264                  181
\end{verbatim}

\begin{Shaded}
\begin{Highlighting}[]
\CommentTok{\# Build the plot}
\FunctionTok{ggplot}\NormalTok{(plot\_data,}
       \FunctionTok{aes}\NormalTok{(}\AttributeTok{x =} \StringTok{\textasciigrave{}}\AttributeTok{HcahpsLinearMeanValue\_Nurse communication}\StringTok{\textasciigrave{}}\NormalTok{,}
           \AttributeTok{y =}\NormalTok{ ExcessReadmissionRatio,}
           \AttributeTok{color =} \StringTok{\textasciigrave{}}\AttributeTok{HcahpsLinearMeanValue\_Overall hospital rating}\StringTok{\textasciigrave{}}\NormalTok{)) }\SpecialCharTok{+}
    \FunctionTok{geom\_point}\NormalTok{(}\AttributeTok{alpha =} \FloatTok{0.55}\NormalTok{, }\AttributeTok{size =} \FloatTok{1.5}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_smooth}\NormalTok{(}\AttributeTok{method =} \StringTok{"lm"}\NormalTok{,}
                \AttributeTok{se =} \ConstantTok{TRUE}\NormalTok{,}
                \AttributeTok{color =} \StringTok{"darkred"}\NormalTok{,}
                \AttributeTok{fill =} \StringTok{"pink"}\NormalTok{,}
                \AttributeTok{linetype =} \StringTok{"dashed"}\NormalTok{,}
                \AttributeTok{linewidth =} \FloatTok{0.8}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{geom\_hline}\NormalTok{(}\AttributeTok{yintercept =} \FloatTok{1.0}\NormalTok{,}
               \AttributeTok{linetype =} \StringTok{"dotted"}\NormalTok{,}
               \AttributeTok{color =} \StringTok{"gray30"}\NormalTok{,}
               \AttributeTok{linewidth =} \FloatTok{0.6}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{facet\_wrap}\NormalTok{(}\SpecialCharTok{\textasciitilde{}}\NormalTok{ DeathRateCategory) }\SpecialCharTok{+}
    \FunctionTok{scale\_color\_viridis\_c}\NormalTok{(}\AttributeTok{option =} \StringTok{"plasma"}\NormalTok{, }\AttributeTok{direction =} \SpecialCharTok{{-}}\DecValTok{1}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{labs}\NormalTok{(}
        \AttributeTok{title    =} \StringTok{"Pneumonia Readmissions vs. Patient Experience"}\NormalTok{,}
        \AttributeTok{subtitle =} \StringTok{"Faceted by mortality performance tier; color reflects overall hospital rating"}\NormalTok{,}
        \AttributeTok{x        =} \StringTok{"Nurse Communication Score (HCAHPS Linear Mean)"}\NormalTok{,}
        \AttributeTok{y        =} \StringTok{"Excess Readmission Ratio (pneumonia)"}\NormalTok{,}
        \AttributeTok{color    =} \StringTok{"Overall}\SpecialCharTok{\textbackslash{}n}\StringTok{Hospital}\SpecialCharTok{\textbackslash{}n}\StringTok{Rating"}\NormalTok{,}
        \AttributeTok{caption  =} \StringTok{"Dotted line = expected ratio of 1.0. Red dashed line = OLS fit with 95\% CI band.}\SpecialCharTok{\textbackslash{}n}\StringTok{Source: CMS Hospital Compare, April 2026."}
\NormalTok{    ) }\SpecialCharTok{+}
    \FunctionTok{theme\_minimal}\NormalTok{(}\AttributeTok{base\_size =} \DecValTok{12}\NormalTok{) }\SpecialCharTok{+}
    \FunctionTok{theme}\NormalTok{(}
        \AttributeTok{plot.title       =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{14}\NormalTok{),}
        \AttributeTok{plot.subtitle    =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{color =} \StringTok{"gray30"}\NormalTok{, }\AttributeTok{size =} \DecValTok{11}\NormalTok{),}
        \AttributeTok{plot.caption     =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{color =} \StringTok{"gray50"}\NormalTok{, }\AttributeTok{size =} \DecValTok{9}\NormalTok{, }\AttributeTok{hjust =} \DecValTok{0}\NormalTok{),}
        \AttributeTok{strip.background =} \FunctionTok{element\_rect}\NormalTok{(}\AttributeTok{fill =} \StringTok{"gray90"}\NormalTok{, }\AttributeTok{color =} \ConstantTok{NA}\NormalTok{),}
        \AttributeTok{strip.text       =} \FunctionTok{element\_text}\NormalTok{(}\AttributeTok{face =} \StringTok{"bold"}\NormalTok{, }\AttributeTok{size =} \DecValTok{11}\NormalTok{),}
        \AttributeTok{legend.position  =} \StringTok{"right"}\NormalTok{,}
        \AttributeTok{panel.spacing    =} \FunctionTok{unit}\NormalTok{(}\FloatTok{1.2}\NormalTok{, }\StringTok{"lines"}\NormalTok{)}
\NormalTok{    )}
\end{Highlighting}
\end{Shaded}

\pandocbounded{\includegraphics[keepaspectratio]{Demo_1_files/figure-latex/unnamed-chunk-37-1.pdf}}

Lastly, make sure to \textbf{interpret} your graphic.

\textbf{Answer:}

This is multivariable storytelling: you'd be able to see whether better
nurse communication correlates with lower readmissions, whether this
relationship holds across mortality tiers, and whether overall rating
reinforces or contradicts the pattern.

The plot shows how pneumonia Excess Readmission Ratios relate to HCAHPS
nurse communication scores across three hospital mortality performance
tiers. Several patterns emerge: (1) Within each panel, the OLS trend
line slopes negatively --- better nurse communication is consistently
associated with lower-than-expected readmission ratios. (2) The ``Worse
than National'' tier (left panel) sits visibly higher than the other
two, with the trend line approaching but not reaching the expected ratio
of 1.0, while the ``Better than National'' tier (right panel) is
centered closer to 1.0 with the steepest slope. (3) The color gradient
(overall hospital rating) reinforces this pattern: lower-rated hospitals
(yellow points) cluster in the upper-left quadrant of each facet (high
readmissions, low communication), while higher-rated hospitals (blue
points) cluster in the lower-right (low readmissions, high
communication). Together, these patterns support the hypothesis that
hospitals performing well on one quality dimension tend to perform well
on others --- patient experience metrics and clinical outcomes are not
independent.

\section*{References}\label{references}
\addcontentsline{toc}{section}{References}

\protect\phantomsection\label{refs}
\begin{CSLReferences}{1}{1}
\bibitem[\citeproctext]{ref-PMID25598730}
De Alba, Israel, and Alpesh Amin. 2014. {``Pneumonia Readmissions: Risk
Factors and Implications.''} \emph{Ochsner Journal} 14 (4): 649--54.

\bibitem[\citeproctext]{ref-R-base}
R Core Team. 2019. \emph{R: A Language and Environment for Statistical
Computing}. R Foundation for Statistical Computing.
\url{https://www.R-project.org}.

\bibitem[\citeproctext]{ref-JSSv059i10}
Wickham, Hadley. 2014. {``Tidy Data.''} \emph{Journal of Statistical
Software} 59 (10): 1--23. \url{https://doi.org/10.18637/jss.v059.i10}.

\end{CSLReferences}

\end{document}
